/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AiCreditsRouteImport } from './routes/ai-credits'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as CompatibilityBuilderRouteImport } from './routes/compatibility-builder'
import { Route as CompatibilityPreviewRouteImport } from './routes/compatibility-preview'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CreatorAccountRouteImport } from './routes/creator-account'
import { Route as CreatorAuthRouteImport } from './routes/creator-auth'
import { Route as CreatorDashboardRouteImport } from './routes/creator-dashboard'
import { Route as CreatorEarningsRouteImport } from './routes/creator-earnings'
import { Route as CreatorExperiencesRouteImport } from './routes/creator-experiences'
import { Route as CreatorGiftsRouteImport } from './routes/creator-gifts'
import { Route as CreatorPaymentsRouteImport } from './routes/creator-payments'
import { Route as CreatorResetPasswordRouteImport } from './routes/creator-reset-password'
import { Route as CreatorStudioRouteImport } from './routes/creator-studio'
import { Route as CreatorTermsRouteImport } from './routes/creator-terms'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as GuessBuilderRouteImport } from './routes/guess-builder'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PaymentTermsRouteImport } from './routes/payment-terms'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StoryBuilderRouteImport } from './routes/story-builder'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TestBuilderRouteImport } from './routes/test-builder'
import { Route as CreatorExperiencesExperienceIdRouteImport } from './routes/creator-experiences_.$experienceId'
import { Route as CreatorCreatorIdRouteImport } from './routes/creator.$creatorId'
import { Route as ExperienceExperienceIdRouteImport } from './routes/experience.$experienceId'
import { Route as PublishSuccessExperienceIdRouteImport } from './routes/publish-success.$experienceId'
import { Route as ShareImageExperienceIdRouteImport } from './routes/share-image.$experienceId'
import { Route as ShareExperienceIdRouteImport } from './routes/share.$experienceId'
import { Route as TestSlugRouteImport } from './routes/test/$slug'
import { Route as TestSlugIndexRouteImport } from './routes/test.$slug.index'
import { Route as TestSlugQuizRouteImport } from './routes/test.$slug.quiz'
import { Route as TestSlugResultRouteImport } from './routes/test.$slug.result'
import { Route as TestSlugPlayRouteImport } from './routes/test/$slug_.play'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCreditsRoute = AiCreditsRouteImport.update({
  id: '/ai-credits',
  path: '/ai-credits',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const CompatibilityBuilderRoute = CompatibilityBuilderRouteImport.update({
  id: '/compatibility-builder',
  path: '/compatibility-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const CompatibilityPreviewRoute = CompatibilityPreviewRouteImport.update({
  id: '/compatibility-preview',
  path: '/compatibility-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorAccountRoute = CreatorAccountRouteImport.update({
  id: '/creator-account',
  path: '/creator-account',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorAuthRoute = CreatorAuthRouteImport.update({
  id: '/creator-auth',
  path: '/creator-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorDashboardRoute = CreatorDashboardRouteImport.update({
  id: '/creator-dashboard',
  path: '/creator-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorEarningsRoute = CreatorEarningsRouteImport.update({
  id: '/creator-earnings',
  path: '/creator-earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorExperiencesRoute = CreatorExperiencesRouteImport.update({
  id: '/creator-experiences',
  path: '/creator-experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorGiftsRoute = CreatorGiftsRouteImport.update({
  id: '/creator-gifts',
  path: '/creator-gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorPaymentsRoute = CreatorPaymentsRouteImport.update({
  id: '/creator-payments',
  path: '/creator-payments',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorResetPasswordRoute = CreatorResetPasswordRouteImport.update({
  id: '/creator-reset-password',
  path: '/creator-reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorStudioRoute = CreatorStudioRouteImport.update({
  id: '/creator-studio',
  path: '/creator-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorTermsRoute = CreatorTermsRouteImport.update({
  id: '/creator-terms',
  path: '/creator-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const GuessBuilderRoute = GuessBuilderRouteImport.update({
  id: '/guess-builder',
  path: '/guess-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentTermsRoute = PaymentTermsRouteImport.update({
  id: '/payment-terms',
  path: '/payment-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryBuilderRoute = StoryBuilderRouteImport.update({
  id: '/story-builder',
  path: '/story-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TestBuilderRoute = TestBuilderRouteImport.update({
  id: '/test-builder',
  path: '/test-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorExperiencesExperienceIdRoute =
  CreatorExperiencesExperienceIdRouteImport.update({
    id: '/creator-experiences_/$experienceId',
    path: '/creator-experiences/$experienceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CreatorCreatorIdRoute = CreatorCreatorIdRouteImport.update({
  id: '/creator/$creatorId',
  path: '/creator/$creatorId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceExperienceIdRoute = ExperienceExperienceIdRouteImport.update({
  id: '/experience/$experienceId',
  path: '/experience/$experienceId',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishSuccessExperienceIdRoute =
  PublishSuccessExperienceIdRouteImport.update({
    id: '/publish-success/$experienceId',
    path: '/publish-success/$experienceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShareImageExperienceIdRoute = ShareImageExperienceIdRouteImport.update({
  id: '/share-image/$experienceId',
  path: '/share-image/$experienceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareExperienceIdRoute = ShareExperienceIdRouteImport.update({
  id: '/share/$experienceId',
  path: '/share/$experienceId',
  getParentRoute: () => rootRouteImport,
} as any)
const TestSlugRoute = TestSlugRouteImport.update({
  id: '/test/$slug',
  path: '/test/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TestSlugIndexRoute = TestSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TestSlugRoute,
} as any)
const TestSlugQuizRoute = TestSlugQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => TestSlugRoute,
} as any)
const TestSlugResultRoute = TestSlugResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => TestSlugRoute,
} as any)
const TestSlugPlayRoute = TestSlugPlayRouteImport.update({
  id: '/test/$slug_/play',
  path: '/test/$slug/play',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/ai-credits': typeof AiCreditsRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/compatibility-builder': typeof CompatibilityBuilderRoute
  '/compatibility-preview': typeof CompatibilityPreviewRoute
  '/cookies': typeof CookiesRoute
  '/create': typeof CreateRoute
  '/creator-account': typeof CreatorAccountRoute
  '/creator-auth': typeof CreatorAuthRoute
  '/creator-dashboard': typeof CreatorDashboardRoute
  '/creator-earnings': typeof CreatorEarningsRoute
  '/creator-experiences': typeof CreatorExperiencesRoute
  '/creator-gifts': typeof CreatorGiftsRoute
  '/creator-payments': typeof CreatorPaymentsRoute
  '/creator-reset-password': typeof CreatorResetPasswordRoute
  '/creator-studio': typeof CreatorStudioRoute
  '/creator-terms': typeof CreatorTermsRoute
  '/examples': typeof ExamplesRoute
  '/guess-builder': typeof GuessBuilderRoute
  '/how-it-works': typeof HowItWorksRoute
  '/payment-terms': typeof PaymentTermsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story-builder': typeof StoryBuilderRoute
  '/terms': typeof TermsRoute
  '/test-builder': typeof TestBuilderRoute
  '/creator-experiences/$experienceId': typeof CreatorExperiencesExperienceIdRoute
  '/creator/$creatorId': typeof CreatorCreatorIdRoute
  '/experience/$experienceId': typeof ExperienceExperienceIdRoute
  '/publish-success/$experienceId': typeof PublishSuccessExperienceIdRoute
  '/share-image/$experienceId': typeof ShareImageExperienceIdRoute
  '/share/$experienceId': typeof ShareExperienceIdRoute
  '/test/$slug': typeof TestSlugRouteWithChildren
  '/test/$slug/quiz': typeof TestSlugQuizRoute
  '/test/$slug/result': typeof TestSlugResultRoute
  '/test/$slug/play': typeof TestSlugPlayRoute
  '/test/$slug/': typeof TestSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/ai-credits': typeof AiCreditsRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/compatibility-builder': typeof CompatibilityBuilderRoute
  '/compatibility-preview': typeof CompatibilityPreviewRoute
  '/cookies': typeof CookiesRoute
  '/create': typeof CreateRoute
  '/creator-account': typeof CreatorAccountRoute
  '/creator-auth': typeof CreatorAuthRoute
  '/creator-dashboard': typeof CreatorDashboardRoute
  '/creator-earnings': typeof CreatorEarningsRoute
  '/creator-experiences': typeof CreatorExperiencesRoute
  '/creator-gifts': typeof CreatorGiftsRoute
  '/creator-payments': typeof CreatorPaymentsRoute
  '/creator-reset-password': typeof CreatorResetPasswordRoute
  '/creator-studio': typeof CreatorStudioRoute
  '/creator-terms': typeof CreatorTermsRoute
  '/examples': typeof ExamplesRoute
  '/guess-builder': typeof GuessBuilderRoute
  '/how-it-works': typeof HowItWorksRoute
  '/payment-terms': typeof PaymentTermsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story-builder': typeof StoryBuilderRoute
  '/terms': typeof TermsRoute
  '/test-builder': typeof TestBuilderRoute
  '/creator-experiences/$experienceId': typeof CreatorExperiencesExperienceIdRoute
  '/creator/$creatorId': typeof CreatorCreatorIdRoute
  '/experience/$experienceId': typeof ExperienceExperienceIdRoute
  '/publish-success/$experienceId': typeof PublishSuccessExperienceIdRoute
  '/share-image/$experienceId': typeof ShareImageExperienceIdRoute
  '/share/$experienceId': typeof ShareExperienceIdRoute
  '/test/$slug/quiz': typeof TestSlugQuizRoute
  '/test/$slug/result': typeof TestSlugResultRoute
  '/test/$slug/play': typeof TestSlugPlayRoute
  '/test/$slug': typeof TestSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/ai-credits': typeof AiCreditsRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/compatibility-builder': typeof CompatibilityBuilderRoute
  '/compatibility-preview': typeof CompatibilityPreviewRoute
  '/cookies': typeof CookiesRoute
  '/create': typeof CreateRoute
  '/creator-account': typeof CreatorAccountRoute
  '/creator-auth': typeof CreatorAuthRoute
  '/creator-dashboard': typeof CreatorDashboardRoute
  '/creator-earnings': typeof CreatorEarningsRoute
  '/creator-experiences': typeof CreatorExperiencesRoute
  '/creator-gifts': typeof CreatorGiftsRoute
  '/creator-payments': typeof CreatorPaymentsRoute
  '/creator-reset-password': typeof CreatorResetPasswordRoute
  '/creator-studio': typeof CreatorStudioRoute
  '/creator-terms': typeof CreatorTermsRoute
  '/examples': typeof ExamplesRoute
  '/guess-builder': typeof GuessBuilderRoute
  '/how-it-works': typeof HowItWorksRoute
  '/payment-terms': typeof PaymentTermsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story-builder': typeof StoryBuilderRoute
  '/terms': typeof TermsRoute
  '/test-builder': typeof TestBuilderRoute
  '/creator-experiences_/$experienceId': typeof CreatorExperiencesExperienceIdRoute
  '/creator/$creatorId': typeof CreatorCreatorIdRoute
  '/experience/$experienceId': typeof ExperienceExperienceIdRoute
  '/publish-success/$experienceId': typeof PublishSuccessExperienceIdRoute
  '/share-image/$experienceId': typeof ShareImageExperienceIdRoute
  '/share/$experienceId': typeof ShareExperienceIdRoute
  '/test/$slug': typeof TestSlugRouteWithChildren
  '/test/$slug/quiz': typeof TestSlugQuizRoute
  '/test/$slug/result': typeof TestSlugResultRoute
  '/test/$slug_/play': typeof TestSlugPlayRoute
  '/test/$slug/': typeof TestSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$username'
    | '/admin'
    | '/admin-login'
    | '/ai-credits'
    | '/community-guidelines'
    | '/compatibility-builder'
    | '/compatibility-preview'
    | '/cookies'
    | '/create'
    | '/creator-account'
    | '/creator-auth'
    | '/creator-dashboard'
    | '/creator-earnings'
    | '/creator-experiences'
    | '/creator-gifts'
    | '/creator-payments'
    | '/creator-reset-password'
    | '/creator-studio'
    | '/creator-terms'
    | '/examples'
    | '/guess-builder'
    | '/how-it-works'
    | '/payment-terms'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/story-builder'
    | '/terms'
    | '/test-builder'
    | '/creator-experiences/$experienceId'
    | '/creator/$creatorId'
    | '/experience/$experienceId'
    | '/publish-success/$experienceId'
    | '/share-image/$experienceId'
    | '/share/$experienceId'
    | '/test/$slug'
    | '/test/$slug/quiz'
    | '/test/$slug/result'
    | '/test/$slug/play'
    | '/test/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$username'
    | '/admin'
    | '/admin-login'
    | '/ai-credits'
    | '/community-guidelines'
    | '/compatibility-builder'
    | '/compatibility-preview'
    | '/cookies'
    | '/create'
    | '/creator-account'
    | '/creator-auth'
    | '/creator-dashboard'
    | '/creator-earnings'
    | '/creator-experiences'
    | '/creator-gifts'
    | '/creator-payments'
    | '/creator-reset-password'
    | '/creator-studio'
    | '/creator-terms'
    | '/examples'
    | '/guess-builder'
    | '/how-it-works'
    | '/payment-terms'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/story-builder'
    | '/terms'
    | '/test-builder'
    | '/creator-experiences/$experienceId'
    | '/creator/$creatorId'
    | '/experience/$experienceId'
    | '/publish-success/$experienceId'
    | '/share-image/$experienceId'
    | '/share/$experienceId'
    | '/test/$slug/quiz'
    | '/test/$slug/result'
    | '/test/$slug/play'
    | '/test/$slug'
  id:
    | '__root__'
    | '/'
    | '/$username'
    | '/admin'
    | '/admin-login'
    | '/ai-credits'
    | '/community-guidelines'
    | '/compatibility-builder'
    | '/compatibility-preview'
    | '/cookies'
    | '/create'
    | '/creator-account'
    | '/creator-auth'
    | '/creator-dashboard'
    | '/creator-earnings'
    | '/creator-experiences'
    | '/creator-gifts'
    | '/creator-payments'
    | '/creator-reset-password'
    | '/creator-studio'
    | '/creator-terms'
    | '/examples'
    | '/guess-builder'
    | '/how-it-works'
    | '/payment-terms'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/story-builder'
    | '/terms'
    | '/test-builder'
    | '/creator-experiences_/$experienceId'
    | '/creator/$creatorId'
    | '/experience/$experienceId'
    | '/publish-success/$experienceId'
    | '/share-image/$experienceId'
    | '/share/$experienceId'
    | '/test/$slug'
    | '/test/$slug/quiz'
    | '/test/$slug/result'
    | '/test/$slug_/play'
    | '/test/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsernameRoute: typeof UsernameRoute
  AdminRoute: typeof AdminRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AiCreditsRoute: typeof AiCreditsRoute
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  CompatibilityBuilderRoute: typeof CompatibilityBuilderRoute
  CompatibilityPreviewRoute: typeof CompatibilityPreviewRoute
  CookiesRoute: typeof CookiesRoute
  CreateRoute: typeof CreateRoute
  CreatorAccountRoute: typeof CreatorAccountRoute
  CreatorAuthRoute: typeof CreatorAuthRoute
  CreatorDashboardRoute: typeof CreatorDashboardRoute
  CreatorEarningsRoute: typeof CreatorEarningsRoute
  CreatorExperiencesRoute: typeof CreatorExperiencesRoute
  CreatorGiftsRoute: typeof CreatorGiftsRoute
  CreatorPaymentsRoute: typeof CreatorPaymentsRoute
  CreatorResetPasswordRoute: typeof CreatorResetPasswordRoute
  CreatorStudioRoute: typeof CreatorStudioRoute
  CreatorTermsRoute: typeof CreatorTermsRoute
  ExamplesRoute: typeof ExamplesRoute
  GuessBuilderRoute: typeof GuessBuilderRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PaymentTermsRoute: typeof PaymentTermsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoryBuilderRoute: typeof StoryBuilderRoute
  TermsRoute: typeof TermsRoute
  TestBuilderRoute: typeof TestBuilderRoute
  CreatorExperiencesExperienceIdRoute: typeof CreatorExperiencesExperienceIdRoute
  CreatorCreatorIdRoute: typeof CreatorCreatorIdRoute
  ExperienceExperienceIdRoute: typeof ExperienceExperienceIdRoute
  PublishSuccessExperienceIdRoute: typeof PublishSuccessExperienceIdRoute
  ShareImageExperienceIdRoute: typeof ShareImageExperienceIdRoute
  ShareExperienceIdRoute: typeof ShareExperienceIdRoute
  TestSlugRoute: typeof TestSlugRouteWithChildren
  TestSlugPlayRoute: typeof TestSlugPlayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-credits': {
      id: '/ai-credits'
      path: '/ai-credits'
      fullPath: '/ai-credits'
      preLoaderRoute: typeof AiCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compatibility-builder': {
      id: '/compatibility-builder'
      path: '/compatibility-builder'
      fullPath: '/compatibility-builder'
      preLoaderRoute: typeof CompatibilityBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compatibility-preview': {
      id: '/compatibility-preview'
      path: '/compatibility-preview'
      fullPath: '/compatibility-preview'
      preLoaderRoute: typeof CompatibilityPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-account': {
      id: '/creator-account'
      path: '/creator-account'
      fullPath: '/creator-account'
      preLoaderRoute: typeof CreatorAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-auth': {
      id: '/creator-auth'
      path: '/creator-auth'
      fullPath: '/creator-auth'
      preLoaderRoute: typeof CreatorAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-dashboard': {
      id: '/creator-dashboard'
      path: '/creator-dashboard'
      fullPath: '/creator-dashboard'
      preLoaderRoute: typeof CreatorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-earnings': {
      id: '/creator-earnings'
      path: '/creator-earnings'
      fullPath: '/creator-earnings'
      preLoaderRoute: typeof CreatorEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-experiences': {
      id: '/creator-experiences'
      path: '/creator-experiences'
      fullPath: '/creator-experiences'
      preLoaderRoute: typeof CreatorExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-gifts': {
      id: '/creator-gifts'
      path: '/creator-gifts'
      fullPath: '/creator-gifts'
      preLoaderRoute: typeof CreatorGiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-payments': {
      id: '/creator-payments'
      path: '/creator-payments'
      fullPath: '/creator-payments'
      preLoaderRoute: typeof CreatorPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-reset-password': {
      id: '/creator-reset-password'
      path: '/creator-reset-password'
      fullPath: '/creator-reset-password'
      preLoaderRoute: typeof CreatorResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-studio': {
      id: '/creator-studio'
      path: '/creator-studio'
      fullPath: '/creator-studio'
      preLoaderRoute: typeof CreatorStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-terms': {
      id: '/creator-terms'
      path: '/creator-terms'
      fullPath: '/creator-terms'
      preLoaderRoute: typeof CreatorTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guess-builder': {
      id: '/guess-builder'
      path: '/guess-builder'
      fullPath: '/guess-builder'
      preLoaderRoute: typeof GuessBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-terms': {
      id: '/payment-terms'
      path: '/payment-terms'
      fullPath: '/payment-terms'
      preLoaderRoute: typeof PaymentTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story-builder': {
      id: '/story-builder'
      path: '/story-builder'
      fullPath: '/story-builder'
      preLoaderRoute: typeof StoryBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-builder': {
      id: '/test-builder'
      path: '/test-builder'
      fullPath: '/test-builder'
      preLoaderRoute: typeof TestBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-experiences_/$experienceId': {
      id: '/creator-experiences_/$experienceId'
      path: '/creator-experiences/$experienceId'
      fullPath: '/creator-experiences/$experienceId'
      preLoaderRoute: typeof CreatorExperiencesExperienceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/$creatorId': {
      id: '/creator/$creatorId'
      path: '/creator/$creatorId'
      fullPath: '/creator/$creatorId'
      preLoaderRoute: typeof CreatorCreatorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/$experienceId': {
      id: '/experience/$experienceId'
      path: '/experience/$experienceId'
      fullPath: '/experience/$experienceId'
      preLoaderRoute: typeof ExperienceExperienceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish-success/$experienceId': {
      id: '/publish-success/$experienceId'
      path: '/publish-success/$experienceId'
      fullPath: '/publish-success/$experienceId'
      preLoaderRoute: typeof PublishSuccessExperienceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share-image/$experienceId': {
      id: '/share-image/$experienceId'
      path: '/share-image/$experienceId'
      fullPath: '/share-image/$experienceId'
      preLoaderRoute: typeof ShareImageExperienceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$experienceId': {
      id: '/share/$experienceId'
      path: '/share/$experienceId'
      fullPath: '/share/$experienceId'
      preLoaderRoute: typeof ShareExperienceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$slug': {
      id: '/test/$slug'
      path: '/test/$slug'
      fullPath: '/test/$slug'
      preLoaderRoute: typeof TestSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$slug/': {
      id: '/test/$slug/'
      path: '/'
      fullPath: '/test/$slug/'
      preLoaderRoute: typeof TestSlugIndexRouteImport
      parentRoute: typeof TestSlugRoute
    }
    '/test/$slug/quiz': {
      id: '/test/$slug/quiz'
      path: '/quiz'
      fullPath: '/test/$slug/quiz'
      preLoaderRoute: typeof TestSlugQuizRouteImport
      parentRoute: typeof TestSlugRoute
    }
    '/test/$slug/result': {
      id: '/test/$slug/result'
      path: '/result'
      fullPath: '/test/$slug/result'
      preLoaderRoute: typeof TestSlugResultRouteImport
      parentRoute: typeof TestSlugRoute
    }
    '/test/$slug_/play': {
      id: '/test/$slug_/play'
      path: '/test/$slug/play'
      fullPath: '/test/$slug/play'
      preLoaderRoute: typeof TestSlugPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TestSlugRouteChildren {
  TestSlugQuizRoute: typeof TestSlugQuizRoute
  TestSlugResultRoute: typeof TestSlugResultRoute
  TestSlugIndexRoute: typeof TestSlugIndexRoute
}

const TestSlugRouteChildren: TestSlugRouteChildren = {
  TestSlugQuizRoute: TestSlugQuizRoute,
  TestSlugResultRoute: TestSlugResultRoute,
  TestSlugIndexRoute: TestSlugIndexRoute,
}

const TestSlugRouteWithChildren = TestSlugRoute._addFileChildren(
  TestSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsernameRoute: UsernameRoute,
  AdminRoute: AdminRoute,
  AdminLoginRoute: AdminLoginRoute,
  AiCreditsRoute: AiCreditsRoute,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  CompatibilityBuilderRoute: CompatibilityBuilderRoute,
  CompatibilityPreviewRoute: CompatibilityPreviewRoute,
  CookiesRoute: CookiesRoute,
  CreateRoute: CreateRoute,
  CreatorAccountRoute: CreatorAccountRoute,
  CreatorAuthRoute: CreatorAuthRoute,
  CreatorDashboardRoute: CreatorDashboardRoute,
  CreatorEarningsRoute: CreatorEarningsRoute,
  CreatorExperiencesRoute: CreatorExperiencesRoute,
  CreatorGiftsRoute: CreatorGiftsRoute,
  CreatorPaymentsRoute: CreatorPaymentsRoute,
  CreatorResetPasswordRoute: CreatorResetPasswordRoute,
  CreatorStudioRoute: CreatorStudioRoute,
  CreatorTermsRoute: CreatorTermsRoute,
  ExamplesRoute: ExamplesRoute,
  GuessBuilderRoute: GuessBuilderRoute,
  HowItWorksRoute: HowItWorksRoute,
  PaymentTermsRoute: PaymentTermsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoryBuilderRoute: StoryBuilderRoute,
  TermsRoute: TermsRoute,
  TestBuilderRoute: TestBuilderRoute,
  CreatorExperiencesExperienceIdRoute: CreatorExperiencesExperienceIdRoute,
  CreatorCreatorIdRoute: CreatorCreatorIdRoute,
  ExperienceExperienceIdRoute: ExperienceExperienceIdRoute,
  PublishSuccessExperienceIdRoute: PublishSuccessExperienceIdRoute,
  ShareImageExperienceIdRoute: ShareImageExperienceIdRoute,
  ShareExperienceIdRoute: ShareExperienceIdRoute,
  TestSlugRoute: TestSlugRouteWithChildren,
  TestSlugPlayRoute: TestSlugPlayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
