import type { AqryoLocale } from "./i18n";

const COPY = {
  "tr": {
    "name": "Uyum Metre",
    "headline": "Bir konu seç. Sorularını ve cevaplarını yaz.",
    "intro": "AQRYO diğer cevap seçeneklerini ve sonuçları hazırlasın. Katılımcılar cevaplasın, senin cevaplarınla ne kadar eşleştiklerini görsün.",
    "examples": "Neler oluşturabilirsin?",
    "hint": "5 soruyla başla, istersen 10’a kadar ekle. Örneklerden birine dokunarak başlığı seçebilirsin.",
    "topic": "Konu / başlık",
    "question": "Soru",
    "answer": "Senin cevabın",
    "add": "Soru ekle",
    "remove": "Kaldır",
    "prepare": "Hazırla →",
    "preparing": "Seçenekler ve sonuçlar hazırlanıyor…",
    "ready": "İçeriğin hazır. Kontrol et ve paylaş.",
    "details": "Soruları ve seçenekleri gör",
    "results": "Yüzdelere göre sonuçlar",
    "preview": "Önizle",
    "publish": "Yayınla",
    "advanced": "Tek tek düzenle",
    "back": "Kolay oluşturucuya dön",
    "error": "Hazırlanamadı. Yazdıkların korunuyor; tekrar deneyebilirsin.",
    "required": "Başlığı, bütün soruları ve cevaplarını doldur.",
    "invalid": "5–10 soru ve her sorunun altında bir cevap olmalı.",
    "long": "Metin çok uzun. Soruları ve cevapları kısalt.",
    "source": "Yayındaki içerik korunur. Düzenlemelerin yeni sürüm olarak yayınlanır.",
    "exampleTitles": [
      "Astroloji: Ne kadar Akrep’sin?",
      "Borsa: Yatırım kafamız ne kadar benziyor?",
      "Dizi: Ne kadar La Casa de Papel’sin?",
      "Aşk: Ne kadar uyumluyuz?",
      "Futbol: Taraftarlık anlayışımız aynı mı?",
      "Müzik: Müzik zevkimiz ne kadar benziyor?",
      "Siyaset: Aynı konularda aynı mı düşünüyoruz?",
      "Oyun: Aynı takımda anlaşır mıydık?",
      "Arkadaşlık: Ne kadar aynı kafadayız?",
      "Girişimcilik: Birlikte şirket kursak anlaşır mıydık?"
    ]
  },
  "en": {
    "name": "Match Meter",
    "headline": "Choose a topic. Write your questions and answers.",
    "intro": "AQRYO prepares the other answer options and results. Participants answer and see how closely their choices match yours.",
    "examples": "What can you create?",
    "hint": "Start with 5 questions; add up to 10. Tap an example to use its title.",
    "topic": "Topic / title",
    "question": "Question",
    "answer": "Your answer",
    "add": "Add question",
    "remove": "Remove",
    "prepare": "Prepare →",
    "preparing": "Preparing options and results…",
    "ready": "Your content is ready. Review and share.",
    "details": "Review questions and options",
    "results": "Results by percentage",
    "preview": "Preview",
    "publish": "Publish",
    "advanced": "Edit individually",
    "back": "Back to simple composer",
    "error": "Could not prepare. Your text is saved; you can try again.",
    "required": "Fill in the title, all questions and your answers.",
    "invalid": "Use 5–10 questions with one answer for each.",
    "long": "The text is too long. Shorten your questions and answers.",
    "source": "Your live content stays unchanged. Edits publish as a new version.",
    "exampleTitles": [
      "Astrology: How Scorpio are you?",
      "Investing: How similar are our investing styles?",
      "TV: How Money Heist are you?",
      "Love: How compatible are we?",
      "Football: Do we support our teams the same way?",
      "Music: How similar are our music tastes?",
      "Politics: Do we think alike on the same issues?",
      "Gaming: Would we work well on the same team?",
      "Friendship: How alike are we?",
      "Business: Would we work well as co-founders?"
    ]
  },
  "es": {
    "name": "Medidor de afinidad",
    "headline": "Elige un tema. Escribe tus preguntas y respuestas.",
    "intro": "AQRYO prepara las otras opciones y los resultados. Los participantes responden y ven cuánto coinciden contigo.",
    "examples": "¿Qué puedes crear?",
    "hint": "Empieza con 5 preguntas y añade hasta 10. Toca un ejemplo para usar su título.",
    "topic": "Tema / título",
    "question": "Pregunta",
    "answer": "Tu respuesta",
    "add": "Añadir pregunta",
    "remove": "Eliminar",
    "prepare": "Preparar →",
    "preparing": "Preparando opciones y resultados…",
    "ready": "Tu contenido está listo. Revísalo y compártelo.",
    "details": "Revisar preguntas y opciones",
    "results": "Resultados por porcentaje",
    "preview": "Vista previa",
    "publish": "Publicar",
    "advanced": "Editar individualmente",
    "back": "Volver al editor sencillo",
    "error": "No se pudo preparar. Tu texto se conserva; puedes reintentar.",
    "required": "Completa el título, las preguntas y tus respuestas.",
    "invalid": "Usa entre 5 y 10 preguntas con una respuesta para cada una.",
    "long": "El texto es demasiado largo. Acorta las preguntas y respuestas.",
    "source": "El contenido publicado se conserva. Los cambios se publican como una nueva versión.",
    "exampleTitles": [
      "Astrología: ¿Cuánto tienes de Escorpio?",
      "Bolsa: ¿Se parecen nuestras formas de invertir?",
      "Series: ¿Cuánto tienes de La Casa de Papel?",
      "Amor: ¿Qué tan compatibles somos?",
      "Fútbol: ¿Vivimos la afición de la misma forma?",
      "Música: ¿Se parecen nuestros gustos?",
      "Política: ¿Pensamos igual sobre los mismos temas?",
      "Videojuegos: ¿Haríamos buen equipo?",
      "Amistad: ¿Qué tanto nos parecemos?",
      "Negocios: ¿Seríamos buenos socios?"
    ]
  },
  "pt": {
    "name": "Medidor de afinidade",
    "headline": "Escolha um tema. Escreva suas perguntas e respostas.",
    "intro": "AQRYO prepara as outras opções e os resultados. Os participantes respondem e veem quanto suas escolhas combinam com as suas.",
    "examples": "O que você pode criar?",
    "hint": "Comece com 5 perguntas e adicione até 10. Toque em um exemplo para usar o título.",
    "topic": "Tema / título",
    "question": "Pergunta",
    "answer": "Sua resposta",
    "add": "Adicionar pergunta",
    "remove": "Remover",
    "prepare": "Preparar →",
    "preparing": "Preparando opções e resultados…",
    "ready": "Seu conteúdo está pronto. Revise e compartilhe.",
    "details": "Revisar perguntas e opções",
    "results": "Resultados por porcentagem",
    "preview": "Prévia",
    "publish": "Publicar",
    "advanced": "Editar individualmente",
    "back": "Voltar ao editor simples",
    "error": "Não foi possível preparar. Seu texto foi mantido; tente novamente.",
    "required": "Preencha o título, todas as perguntas e suas respostas.",
    "invalid": "Use de 5 a 10 perguntas com uma resposta para cada.",
    "long": "O texto é longo demais. Encurte as perguntas e respostas.",
    "source": "O conteúdo publicado será mantido. As alterações criam uma nova versão.",
    "exampleTitles": [
      "Astrologia: Quanto de Escorpião você tem?",
      "Bolsa: Nossos estilos de investir são parecidos?",
      "Séries: Quanto de La Casa de Papel você tem?",
      "Amor: Quanto combinamos?",
      "Futebol: Torcemos do mesmo jeito?",
      "Música: Nossos gostos são parecidos?",
      "Política: Pensamos igual sobre os mesmos temas?",
      "Jogos: Formaríamos uma boa equipe?",
      "Amizade: Quanto pensamos parecido?",
      "Negócios: Seríamos bons sócios?"
    ]
  },
  "fr": {
    "name": "Mesure d’affinité",
    "headline": "Choisissez un sujet. Écrivez vos questions et réponses.",
    "intro": "AQRYO prépare les autres choix et les résultats. Les participants répondent et découvrent à quel point leurs choix correspondent aux vôtres.",
    "examples": "Que pouvez-vous créer ?",
    "hint": "Commencez avec 5 questions, jusqu’à 10. Touchez un exemple pour utiliser son titre.",
    "topic": "Sujet / titre",
    "question": "Question",
    "answer": "Votre réponse",
    "add": "Ajouter une question",
    "remove": "Supprimer",
    "prepare": "Préparer →",
    "preparing": "Préparation des choix et résultats…",
    "ready": "Votre contenu est prêt. Vérifiez et partagez.",
    "details": "Voir les questions et choix",
    "results": "Résultats par pourcentage",
    "preview": "Aperçu",
    "publish": "Publier",
    "advanced": "Modifier séparément",
    "back": "Revenir à l’éditeur simple",
    "error": "La préparation a échoué. Votre texte est conservé ; réessayez.",
    "required": "Remplissez le titre, toutes les questions et vos réponses.",
    "invalid": "Utilisez 5 à 10 questions avec une réponse pour chacune.",
    "long": "Le texte est trop long. Raccourcissez les questions et réponses.",
    "source": "Le contenu publié est conservé. Les modifications créent une nouvelle version.",
    "exampleTitles": [
      "Astrologie : À quel point êtes-vous Scorpion ?",
      "Bourse : Nos façons d’investir se ressemblent-elles ?",
      "Séries : À quel point êtes-vous La Casa de Papel ?",
      "Amour : Sommes-nous compatibles ?",
      "Football : Vivons-nous notre passion de la même façon ?",
      "Musique : Nos goûts se ressemblent-ils ?",
      "Politique : Pensons-nous pareil sur les mêmes sujets ?",
      "Jeux : Ferions-nous une bonne équipe ?",
      "Amitié : Sommes-nous sur la même longueur d’onde ?",
      "Entrepreneuriat : Serions-nous de bons associés ?"
    ]
  },
  "de": {
    "name": "Übereinstimmungs-Meter",
    "headline": "Wähle ein Thema. Schreibe deine Fragen und Antworten.",
    "intro": "AQRYO erstellt weitere Antwortmöglichkeiten und Ergebnisse. Teilnehmer antworten und sehen, wie sehr ihre Auswahl deiner entspricht.",
    "examples": "Was kannst du erstellen?",
    "hint": "Starte mit 5 Fragen und ergänze bis zu 10. Tippe auf ein Beispiel, um den Titel zu verwenden.",
    "topic": "Thema / Titel",
    "question": "Frage",
    "answer": "Deine Antwort",
    "add": "Frage hinzufügen",
    "remove": "Entfernen",
    "prepare": "Erstellen →",
    "preparing": "Antwortmöglichkeiten und Ergebnisse werden erstellt…",
    "ready": "Dein Inhalt ist bereit. Prüfe und teile ihn.",
    "details": "Fragen und Antworten ansehen",
    "results": "Ergebnisse nach Prozent",
    "preview": "Vorschau",
    "publish": "Veröffentlichen",
    "advanced": "Einzeln bearbeiten",
    "back": "Zurück zum einfachen Editor",
    "error": "Erstellung fehlgeschlagen. Dein Text bleibt erhalten; versuche es erneut.",
    "required": "Fülle Titel, alle Fragen und deine Antworten aus.",
    "invalid": "Nutze 5–10 Fragen mit je einer Antwort.",
    "long": "Der Text ist zu lang. Kürze Fragen und Antworten.",
    "source": "Dein veröffentlichter Inhalt bleibt erhalten. Änderungen werden als neue Version veröffentlicht.",
    "exampleTitles": [
      "Astrologie: Wie viel Skorpion steckt in dir?",
      "Börse: Wie ähnlich investieren wir?",
      "Serien: Wie viel Haus des Geldes steckt in dir?",
      "Liebe: Wie gut passen wir zusammen?",
      "Fußball: Leben wir unsere Fanliebe gleich?",
      "Musik: Wie ähnlich ist unser Musikgeschmack?",
      "Politik: Denken wir über dieselben Themen gleich?",
      "Gaming: Wären wir ein gutes Team?",
      "Freundschaft: Wie ähnlich ticken wir?",
      "Gründen: Wären wir gute Geschäftspartner?"
    ]
  },
  "it": {
    "name": "Misuratore di affinità",
    "headline": "Scegli un tema. Scrivi domande e risposte.",
    "intro": "AQRYO prepara le altre opzioni e i risultati. I partecipanti rispondono e scoprono quanto le loro scelte coincidono con le tue.",
    "examples": "Cosa puoi creare?",
    "hint": "Inizia con 5 domande e aggiungine fino a 10. Tocca un esempio per usarne il titolo.",
    "topic": "Tema / titolo",
    "question": "Domanda",
    "answer": "La tua risposta",
    "add": "Aggiungi domanda",
    "remove": "Rimuovi",
    "prepare": "Prepara →",
    "preparing": "Preparazione di opzioni e risultati…",
    "ready": "Il contenuto è pronto. Controlla e condividi.",
    "details": "Controlla domande e opzioni",
    "results": "Risultati per percentuale",
    "preview": "Anteprima",
    "publish": "Pubblica",
    "advanced": "Modifica singolarmente",
    "back": "Torna all’editor semplice",
    "error": "Preparazione non riuscita. Il testo è conservato; riprova.",
    "required": "Compila il titolo, tutte le domande e le tue risposte.",
    "invalid": "Usa da 5 a 10 domande con una risposta ciascuna.",
    "long": "Il testo è troppo lungo. Accorcia domande e risposte.",
    "source": "Il contenuto pubblicato resta invariato. Le modifiche creano una nuova versione.",
    "exampleTitles": [
      "Astrologia: Quanto sei Scorpione?",
      "Borsa: Quanto si somigliano i nostri investimenti?",
      "Serie: Quanto sei La Casa di Carta?",
      "Amore: Quanto siamo compatibili?",
      "Calcio: Viviamo il tifo allo stesso modo?",
      "Musica: Quanto si somigliano i nostri gusti?",
      "Politica: Pensiamo allo stesso modo sugli stessi temi?",
      "Giochi: Formeremmo una buona squadra?",
      "Amicizia: Quanto siamo sulla stessa lunghezza d’onda?",
      "Impresa: Saremmo buoni soci?"
    ]
  },
  "ar": {
    "name": "مقياس التوافق",
    "headline": "اختر موضوعًا. اكتب أسئلتك وإجاباتك.",
    "intro": "تجهز AQRYO خيارات الإجابة الأخرى والنتائج. يجيب المشاركون ويعرفون مدى تطابق اختياراتهم مع إجاباتك.",
    "examples": "ماذا يمكنك إنشاءه؟",
    "hint": "ابدأ بـ5 أسئلة وأضف حتى 10. اضغط على مثال لاستخدام عنوانه.",
    "topic": "الموضوع / العنوان",
    "question": "السؤال",
    "answer": "إجابتك",
    "add": "أضف سؤالًا",
    "remove": "إزالة",
    "prepare": "جهّز ←",
    "preparing": "جارٍ تجهيز الخيارات والنتائج…",
    "ready": "المحتوى جاهز. راجعه وشاركه.",
    "details": "راجع الأسئلة والخيارات",
    "results": "النتائج حسب النسبة",
    "preview": "معاينة",
    "publish": "نشر",
    "advanced": "تعديل كل عنصر",
    "back": "العودة للمحرر المبسط",
    "error": "تعذر التجهيز. نصك محفوظ؛ يمكنك المحاولة مجددًا.",
    "required": "أكمل العنوان وكل الأسئلة وإجاباتك.",
    "invalid": "استخدم من 5 إلى 10 أسئلة مع إجابة لكل سؤال.",
    "long": "النص طويل جدًا. اختصر الأسئلة والإجابات.",
    "source": "يبقى المحتوى المنشور كما هو. تُنشر التعديلات كنسخة جديدة.",
    "exampleTitles": [
      "الأبراج: إلى أي مدى تشبه برج العقرب؟",
      "الاستثمار: هل تتشابه أساليبنا في الاستثمار؟",
      "المسلسلات: إلى أي مدى تشبه عالم لا كاسا دي بابيل؟",
      "الحب: ما مدى توافقنا؟",
      "كرة القدم: هل نشجع بالطريقة نفسها؟",
      "الموسيقى: هل تتشابه أذواقنا؟",
      "السياسة: هل نفكر بالطريقة نفسها؟",
      "الألعاب: هل ننجح في فريق واحد؟",
      "الصداقة: ما مدى تشابهنا؟",
      "الأعمال: هل ننجح كشريكين؟"
    ]
  },
  "hi": {
    "name": "मेल मीटर",
    "headline": "विषय चुनें। अपने सवाल और जवाब लिखें।",
    "intro": "AQRYO दूसरे जवाबों के विकल्प और नतीजे बनाएगा। प्रतिभागी जवाब देकर देखेंगे कि उनके चुनाव आपसे कितने मिलते हैं।",
    "examples": "आप क्या बना सकते हैं?",
    "hint": "5 सवालों से शुरू करें और 10 तक जोड़ें। उदाहरण का शीर्षक चुनने के लिए उसे टैप करें।",
    "topic": "विषय / शीर्षक",
    "question": "सवाल",
    "answer": "आपका जवाब",
    "add": "सवाल जोड़ें",
    "remove": "हटाएँ",
    "prepare": "तैयार करें →",
    "preparing": "विकल्प और नतीजे तैयार हो रहे हैं…",
    "ready": "कंटेंट तैयार है। जाँचें और शेयर करें।",
    "details": "सवाल और विकल्प देखें",
    "results": "प्रतिशत के अनुसार नतीजे",
    "preview": "पूर्वावलोकन",
    "publish": "प्रकाशित करें",
    "advanced": "अलग-अलग बदलें",
    "back": "सरल संपादक पर लौटें",
    "error": "तैयार नहीं हो सका। आपका टेक्स्ट सुरक्षित है; फिर कोशिश करें।",
    "required": "शीर्षक, सभी सवाल और अपने जवाब भरें।",
    "invalid": "हर सवाल के एक जवाब के साथ 5–10 सवाल लिखें।",
    "long": "टेक्स्ट बहुत लंबा है। सवाल और जवाब छोटे करें।",
    "source": "प्रकाशित कंटेंट सुरक्षित रहेगा। बदलाव नए संस्करण के रूप में प्रकाशित होंगे।",
    "exampleTitles": [
      "ज्योतिष: आप कितने वृश्चिक हैं?",
      "निवेश: हमारी निवेश सोच कितनी मिलती है?",
      "सीरीज़: आप कितने मनी हाइस्ट हैं?",
      "प्यार: हम कितने अनुकूल हैं?",
      "फुटबॉल: क्या हम एक जैसे प्रशंसक हैं?",
      "संगीत: हमारी पसंद कितनी मिलती है?",
      "राजनीति: क्या मुद्दों पर हमारी सोच एक है?",
      "गेमिंग: क्या हम अच्छी टीम बनेंगे?",
      "दोस्ती: हमारी सोच कितनी मिलती है?",
      "व्यवसाय: क्या हम अच्छे सह-संस्थापक बनेंगे?"
    ]
  },
  "id": {
    "name": "Pengukur kecocokan",
    "headline": "Pilih topik. Tulis pertanyaan dan jawabanmu.",
    "intro": "AQRYO menyiapkan pilihan jawaban lain dan hasilnya. Peserta menjawab dan melihat seberapa cocok pilihan mereka dengan jawabanmu.",
    "examples": "Apa yang bisa kamu buat?",
    "hint": "Mulai dengan 5 pertanyaan, tambah hingga 10. Ketuk contoh untuk memakai judulnya.",
    "topic": "Topik / judul",
    "question": "Pertanyaan",
    "answer": "Jawabanmu",
    "add": "Tambah pertanyaan",
    "remove": "Hapus",
    "prepare": "Siapkan →",
    "preparing": "Menyiapkan pilihan dan hasil…",
    "ready": "Kontenmu siap. Periksa dan bagikan.",
    "details": "Lihat pertanyaan dan pilihan",
    "results": "Hasil berdasarkan persentase",
    "preview": "Pratinjau",
    "publish": "Terbitkan",
    "advanced": "Edit satu per satu",
    "back": "Kembali ke editor sederhana",
    "error": "Gagal menyiapkan. Teksmu tersimpan; coba lagi.",
    "required": "Isi judul, semua pertanyaan dan jawabanmu.",
    "invalid": "Gunakan 5–10 pertanyaan dengan satu jawaban per pertanyaan.",
    "long": "Teks terlalu panjang. Persingkat pertanyaan dan jawaban.",
    "source": "Konten terbit tetap tersimpan. Perubahan diterbitkan sebagai versi baru.",
    "exampleTitles": [
      "Astrologi: Seberapa Scorpio kamu?",
      "Investasi: Seberapa mirip cara investasi kita?",
      "Serial: Seberapa Money Heist kamu?",
      "Cinta: Seberapa cocok kita?",
      "Sepak bola: Apakah cara kita mendukung tim sama?",
      "Musik: Seberapa mirip selera musik kita?",
      "Politik: Apakah kita sepemikiran?",
      "Game: Apakah kita cocok dalam satu tim?",
      "Persahabatan: Seberapa mirip kita?",
      "Bisnis: Apakah kita cocok jadi rekan pendiri?"
    ]
  },
  "ru": {
    "name": "Измеритель совпадений",
    "headline": "Выберите тему. Напишите вопросы и ответы.",
    "intro": "AQRYO подготовит другие варианты ответов и результаты. Участники ответят и увидят, насколько их выбор совпадает с вашим.",
    "examples": "Что можно создать?",
    "hint": "Начните с 5 вопросов, добавьте до 10. Нажмите на пример, чтобы выбрать заголовок.",
    "topic": "Тема / заголовок",
    "question": "Вопрос",
    "answer": "Ваш ответ",
    "add": "Добавить вопрос",
    "remove": "Удалить",
    "prepare": "Подготовить →",
    "preparing": "Готовим варианты и результаты…",
    "ready": "Контент готов. Проверьте и поделитесь.",
    "details": "Посмотреть вопросы и варианты",
    "results": "Результаты по процентам",
    "preview": "Предпросмотр",
    "publish": "Опубликовать",
    "advanced": "Редактировать отдельно",
    "back": "Вернуться в простой редактор",
    "error": "Не удалось подготовить. Текст сохранён; попробуйте ещё раз.",
    "required": "Заполните заголовок, все вопросы и ответы.",
    "invalid": "Используйте 5–10 вопросов с одним ответом на каждый.",
    "long": "Текст слишком длинный. Сократите вопросы и ответы.",
    "source": "Опубликованный контент сохранится. Изменения публикуются как новая версия.",
    "exampleTitles": [
      "Астрология: Насколько ты Скорпион?",
      "Биржа: Насколько похожи наши подходы к инвестициям?",
      "Сериалы: Насколько ты «Бумажный дом»?",
      "Любовь: Насколько мы совместимы?",
      "Футбол: Одинаково ли мы болеем?",
      "Музыка: Насколько похожи наши вкусы?",
      "Политика: Одинаково ли мы думаем об этих темах?",
      "Игры: Сработались бы мы в одной команде?",
      "Дружба: Насколько мы похожи?",
      "Бизнес: Стали бы мы хорошими партнёрами?"
    ]
  },
  "bn": {
    "name": "মিল মিটার",
    "headline": "একটি বিষয় বেছে নিন। প্রশ্ন ও উত্তর লিখুন।",
    "intro": "AQRYO অন্য উত্তরের বিকল্প ও ফলাফল তৈরি করবে। অংশগ্রহণকারীরা উত্তর দিয়ে দেখবে তাদের পছন্দ আপনার সঙ্গে কতটা মেলে।",
    "examples": "কী তৈরি করতে পারেন?",
    "hint": "5টি প্রশ্ন দিয়ে শুরু করুন, 10টি পর্যন্ত যোগ করুন। শিরোনাম নিতে উদাহরণে চাপুন।",
    "topic": "বিষয় / শিরোনাম",
    "question": "প্রশ্ন",
    "answer": "আপনার উত্তর",
    "add": "প্রশ্ন যোগ করুন",
    "remove": "সরান",
    "prepare": "তৈরি করুন →",
    "preparing": "বিকল্প ও ফলাফল তৈরি হচ্ছে…",
    "ready": "কনটেন্ট প্রস্তুত। যাচাই করে শেয়ার করুন।",
    "details": "প্রশ্ন ও বিকল্প দেখুন",
    "results": "শতাংশ অনুযায়ী ফলাফল",
    "preview": "প্রিভিউ",
    "publish": "প্রকাশ করুন",
    "advanced": "আলাদা করে সম্পাদনা",
    "back": "সহজ সম্পাদকে ফিরুন",
    "error": "তৈরি করা যায়নি। লেখা সংরক্ষিত আছে; আবার চেষ্টা করুন।",
    "required": "শিরোনাম, সব প্রশ্ন ও উত্তর পূরণ করুন।",
    "invalid": "প্রতিটি প্রশ্নের একটি উত্তরসহ 5–10টি প্রশ্ন দিন।",
    "long": "লেখা বেশি দীর্ঘ। প্রশ্ন ও উত্তর ছোট করুন।",
    "source": "প্রকাশিত কনটেন্ট থাকবে। পরিবর্তন নতুন সংস্করণে প্রকাশ হবে।",
    "exampleTitles": [
      "জ্যোতিষ: আপনি কতটা বৃশ্চিক?",
      "বিনিয়োগ: আমাদের বিনিয়োগের ভাবনা কতটা মেলে?",
      "সিরিজ: আপনি কতটা মানি হাইস্ট?",
      "প্রেম: আমরা কতটা মানানসই?",
      "ফুটবল: আমরা কি একইভাবে দলকে সমর্থন করি?",
      "সংগীত: আমাদের পছন্দ কতটা মেলে?",
      "রাজনীতি: একই বিষয়ে কি একই ভাবি?",
      "গেম: আমরা কি ভালো দল হব?",
      "বন্ধুত্ব: আমরা কতটা একই রকম?",
      "ব্যবসা: আমরা কি ভালো সহপ্রতিষ্ঠাতা হব?"
    ]
  },
  "ur": {
    "name": "مطابقت میٹر",
    "headline": "موضوع منتخب کریں۔ اپنے سوالات اور جوابات لکھیں۔",
    "intro": "AQRYO جواب کے دوسرے اختیارات اور نتائج تیار کرے گا۔ شرکاء جواب دیں گے اور دیکھیں گے کہ ان کے انتخاب آپ سے کتنے ملتے ہیں۔",
    "examples": "آپ کیا بنا سکتے ہیں؟",
    "hint": "5 سوالات سے شروع کریں، 10 تک شامل کریں۔ عنوان لینے کے لیے مثال پر ٹیپ کریں۔",
    "topic": "موضوع / عنوان",
    "question": "سوال",
    "answer": "آپ کا جواب",
    "add": "سوال شامل کریں",
    "remove": "ہٹائیں",
    "prepare": "تیار کریں ←",
    "preparing": "اختیارات اور نتائج تیار ہو رہے ہیں…",
    "ready": "مواد تیار ہے۔ دیکھیں اور شیئر کریں۔",
    "details": "سوالات اور اختیارات دیکھیں",
    "results": "فیصد کے مطابق نتائج",
    "preview": "پیش منظر",
    "publish": "شائع کریں",
    "advanced": "الگ الگ ترمیم",
    "back": "سادہ ایڈیٹر پر واپس",
    "error": "تیار نہیں ہو سکا۔ متن محفوظ ہے؛ دوبارہ کوشش کریں۔",
    "required": "عنوان، تمام سوالات اور اپنے جوابات مکمل کریں۔",
    "invalid": "ہر سوال کے ایک جواب کے ساتھ 5–10 سوالات لکھیں۔",
    "long": "متن بہت طویل ہے۔ سوالات اور جوابات مختصر کریں۔",
    "source": "شائع شدہ مواد محفوظ رہتا ہے۔ تبدیلیاں نئے نسخے میں شائع ہوتی ہیں۔",
    "exampleTitles": [
      "نجوم: آپ کتنے عقرب ہیں؟",
      "سرمایہ کاری: ہماری سوچ کتنی ملتی ہے؟",
      "سیریز: آپ کتنے منی ہائسٹ ہیں؟",
      "محبت: ہم کتنے موافق ہیں؟",
      "فٹبال: کیا ہم ایک جیسے مداح ہیں؟",
      "موسیقی: ہماری پسند کتنی ملتی ہے؟",
      "سیاست: کیا ان موضوعات پر ہماری سوچ ایک ہے؟",
      "گیمنگ: کیا ہم اچھی ٹیم بنیں گے؟",
      "دوستی: ہماری سوچ کتنی ملتی ہے؟",
      "کاروبار: کیا ہم اچھے شریک بانی بنیں گے؟"
    ]
  },
  "vi": {
    "name": "Thước đo tương đồng",
    "headline": "Chọn chủ đề. Viết câu hỏi và câu trả lời.",
    "intro": "AQRYO chuẩn bị các lựa chọn khác và kết quả. Người tham gia trả lời và xem lựa chọn của họ giống bạn đến đâu.",
    "examples": "Bạn có thể tạo gì?",
    "hint": "Bắt đầu với 5 câu hỏi, thêm tối đa 10. Chạm ví dụ để dùng tiêu đề.",
    "topic": "Chủ đề / tiêu đề",
    "question": "Câu hỏi",
    "answer": "Câu trả lời của bạn",
    "add": "Thêm câu hỏi",
    "remove": "Xóa",
    "prepare": "Chuẩn bị →",
    "preparing": "Đang chuẩn bị lựa chọn và kết quả…",
    "ready": "Nội dung đã sẵn sàng. Kiểm tra và chia sẻ.",
    "details": "Xem câu hỏi và lựa chọn",
    "results": "Kết quả theo phần trăm",
    "preview": "Xem trước",
    "publish": "Đăng",
    "advanced": "Chỉnh từng mục",
    "back": "Trở về trình soạn đơn giản",
    "error": "Không thể chuẩn bị. Văn bản được giữ lại; hãy thử lại.",
    "required": "Điền tiêu đề, mọi câu hỏi và câu trả lời.",
    "invalid": "Dùng 5–10 câu hỏi với một câu trả lời cho mỗi câu.",
    "long": "Văn bản quá dài. Rút ngắn câu hỏi và câu trả lời.",
    "source": "Nội dung đã đăng được giữ nguyên. Chỉnh sửa được đăng thành phiên bản mới.",
    "exampleTitles": [
      "Chiêm tinh: Bạn giống Bọ Cạp đến đâu?",
      "Đầu tư: Cách đầu tư của chúng ta giống nhau đến đâu?",
      "Phim: Bạn giống thế giới Money Heist đến đâu?",
      "Tình yêu: Chúng ta hợp nhau đến đâu?",
      "Bóng đá: Chúng ta cổ vũ giống nhau không?",
      "Âm nhạc: Gu nhạc giống nhau đến đâu?",
      "Chính trị: Chúng ta nghĩ giống nhau về các vấn đề không?",
      "Game: Chúng ta có hợp cùng đội không?",
      "Tình bạn: Chúng ta giống nhau đến đâu?",
      "Kinh doanh: Chúng ta có hợp làm đồng sáng lập không?"
    ]
  },
  "fil": {
    "name": "Sukatan ng pagkakatugma",
    "headline": "Pumili ng paksa. Isulat ang tanong at sagot mo.",
    "intro": "Ihahanda ng AQRYO ang ibang pagpipilian at resulta. Sasagot ang participants at makikita kung gaano katugma ang mga pinili nila sa iyo.",
    "examples": "Ano ang puwede mong gawin?",
    "hint": "Magsimula sa 5 tanong, hanggang 10. I-tap ang halimbawa para gamitin ang pamagat.",
    "topic": "Paksa / pamagat",
    "question": "Tanong",
    "answer": "Sagot mo",
    "add": "Magdagdag ng tanong",
    "remove": "Alisin",
    "prepare": "Ihanda →",
    "preparing": "Inihahanda ang mga pagpipilian at resulta…",
    "ready": "Handa na ang content. Suriin at i-share.",
    "details": "Tingnan ang tanong at pagpipilian",
    "results": "Mga resulta ayon sa porsiyento",
    "preview": "Preview",
    "publish": "I-publish",
    "advanced": "I-edit isa-isa",
    "back": "Bumalik sa simpleng editor",
    "error": "Hindi naihanda. Naka-save ang teksto; subukang muli.",
    "required": "Punan ang pamagat, lahat ng tanong at sagot.",
    "invalid": "Gumamit ng 5–10 tanong na may tig-isang sagot.",
    "long": "Masyadong mahaba ang teksto. Paikliin ang tanong at sagot.",
    "source": "Mananatili ang nai-publish na content. Bagong bersyon ang mga pagbabago.",
    "exampleTitles": [
      "Astrolohiya: Gaano ka ka-Scorpio?",
      "Pamumuhunan: Gaano kapareho ang estilo natin?",
      "Serye: Gaano ka ka-Money Heist?",
      "Pag-ibig: Gaano tayo katugma?",
      "Football: Pareho ba ang paraan natin ng pagsuporta?",
      "Musika: Gaano kapareho ang gusto nating musika?",
      "Politika: Pareho ba tayo ng pananaw?",
      "Gaming: Magiging mahusay ba tayong magkakampi?",
      "Pagkakaibigan: Gaano tayo kapareho?",
      "Negosyo: Magiging mahusay ba tayong magkasosyo?"
    ]
  }
} satisfies Record<AqryoLocale, { name: string; headline: string; intro: string; examples: string; hint: string; topic: string; question: string; answer: string; add: string; remove: string; prepare: string; preparing: string; ready: string; details: string; results: string; preview: string; publish: string; advanced: string; back: string; error: string; required: string; invalid: string; long: string; source: string; exampleTitles: string[] }>;

export function getCompatibilityCopy(locale: string) { return COPY[locale as AqryoLocale] ?? COPY.en; }
