import type { AqryoLocale } from "./i18n";

const copy = {
  "en": {
    "mine": "My experiences",
    "active": "Active",
    "views": "Views",
    "engagement": "Engagement",
    "completions": "Completions",
    "allExperiences": "All experiences",
    "search": "Search experiences",
    "statusFilter": "Status filter",
    "allStatuses": "All statuses",
    "paused": "Paused",
    "draft": "Draft",
    "sort": "Sort experiences",
    "newest": "Newest",
    "oldest": "Oldest",
    "mostViewed": "Most viewed",
    "mostEngaged": "Most engagement",
    "mostCompleted": "Most completed",
    "loading": "Loading experiences…",
    "status": "Status",
    "lastActivity": "Last activity",
    "noResults": "No results found",
    "changeFilters": "Change your search or filters.",
    "experiences": "Experiences",
    "starts": "Starts",
    "responses": "Responses",
    "moderation": "Moderation",
    "archived": "Archived",
    "noActivity": "None yet",
    "publishedOn": "Published {date}",
    "unknown": "Unknown",
    "story": "Story / Content",
    "questionConfession": "Question or Confession?",
    "compatibility": "Love Meter",
    "guess": "Guess / What is it?",
    "recommendation": "Recommendation",
    "decision": "Opinion & Decision",
    "guided": "Guided",
    "score": "Correct answer / Score",
    "spectrum": "How much X are you?",
    "archetype": "Which X are you?",
    "emptyTitle": "No experiences yet",
    "emptyHint": "Your first published experience will appear here.",
    "newExperience": "New experience",
    "view": "View ↗",
    "edit": "Edit content",
    "opening": "Opening content…",
    "updating": "Updating…",
    "pause": "Pause",
    "republish": "Republish",
    "closeShare": "Close sharing",
    "share": "Share",
    "copyLink": "Copy link",
    "copied": "Copied ✓",
    "shareOnX": "Share on X",
    "participants": "Participants",
    "loadingParticipants": "Loading participants…",
    "noParticipants": "No completions yet.",
    "anonymous": "Anonymous",
    "result": "Result",
    "completed": "Completed",
    "correct": "Correct",
    "answers": "Answers given",
    "question": "Question",
    "option": "Option",
    "participantAnswer": "Participant’s answer",
    "shareHeading": "Share your experience.",
    "shareHint": "Copy the link or share on social channels.",
    "qrCode": "QR code",
    "qrAlt": "Experience QR code",
    "qrHint": "Use it in physical spaces or on another image.",
    "openQr": "Open QR ↗",
    "participantsHint": "Most recent completions appear first.",
    "storyNoData": "This experience does not collect question-and-answer data.",
    "guessNoData": "Guess completed. The free-text answer is not stored in this record.",
    "completionNoData": "No answer details for this completion.",
    "moderationLock": "Moderation lock",
    "moderationPaused": "AQRYO moderation has paused this experience.",
    "cannotRepublish": "Creators cannot republish it.",
    "reason": "Reason"
  },
  "tr": {
    "mine": "Experience’larım",
    "active": "Aktif",
    "views": "Görüntüleme",
    "engagement": "Etkileşim",
    "completions": "Tamamlama",
    "allExperiences": "Tüm Experience’lar",
    "search": "Experience ara",
    "statusFilter": "Durum filtresi",
    "allStatuses": "Tüm durumlar",
    "paused": "Pasif",
    "draft": "Taslak",
    "sort": "Experience sıralaması",
    "newest": "En yeni",
    "oldest": "En eski",
    "mostViewed": "En çok görüntülenen",
    "mostEngaged": "En çok etkileşim",
    "mostCompleted": "En çok tamamlanan",
    "loading": "Experience’lar yükleniyor…",
    "status": "Durum",
    "lastActivity": "Son aktivite",
    "noResults": "Sonuç bulunamadı",
    "changeFilters": "Arama veya filtrelerini değiştir.",
    "experiences": "Experience’lar",
    "starts": "Başlatma",
    "responses": "Gelen",
    "moderation": "Moderasyon",
    "archived": "Arşiv",
    "noActivity": "Henüz yok",
    "publishedOn": "{date} tarihinde yayınlandı",
    "unknown": "Bilinmiyor",
    "story": "Hikâye / İçerik",
    "questionConfession": "Soru mu İtiraf mı?",
    "compatibility": "Aşk Metre",
    "guess": "Tahmin et / Bu nedir?",
    "recommendation": "Öneri",
    "decision": "Görüş & Karar",
    "guided": "Yönlendirmeli",
    "score": "Doğru cevap / Skor",
    "spectrum": "Ne kadar X’sin?",
    "archetype": "Hangi X’sin?",
    "emptyTitle": "Henüz Experience yok",
    "emptyHint": "İlk Experience’ını yayınladığında burada görünecek.",
    "newExperience": "Yeni Experience",
    "view": "Gör ↗",
    "edit": "İçeriği düzenle",
    "opening": "İçerik açılıyor…",
    "updating": "Güncelleniyor…",
    "pause": "Pasife al",
    "republish": "Yeniden yayınla",
    "closeShare": "Paylaşımı kapat",
    "share": "Paylaş",
    "copyLink": "Linki kopyala",
    "copied": "Kopyalandı ✓",
    "shareOnX": "X’te paylaş",
    "participants": "Katılımcılar",
    "loadingParticipants": "Katılımcılar yükleniyor…",
    "noParticipants": "Henüz tamamlayan yok.",
    "anonymous": "Anonim",
    "result": "Sonuç",
    "completed": "Tamamlandı",
    "correct": "Doğru",
    "answers": "Verilen cevaplar",
    "question": "Soru",
    "option": "Seçenek",
    "participantAnswer": "Katılımcının cevabı",
    "shareHeading": "Experience’ını dışarı taşı.",
    "shareHint": "Linki kopyala veya doğrudan sosyal kanallarda paylaş.",
    "qrCode": "QR kod",
    "qrAlt": "Experience QR kodu",
    "qrHint": "Fiziksel ortamda veya başka bir görselin üzerinde kullan.",
    "openQr": "QR’ı aç ↗",
    "participantsHint": "En yeni tamamlamalar önce gösterilir.",
    "storyNoData": "Bu Experience soru-cevap verisi üretmiyor.",
    "guessNoData": "Tahmin tamamlandı. Serbest cevap metni bu kayıtta saklanmıyor.",
    "completionNoData": "Bu tamamlamada cevap detayı yok.",
    "moderationLock": "Moderasyon kilidi",
    "moderationPaused": "Bu Experience AQRYO moderasyonu tarafından durduruldu.",
    "cannotRepublish": "Yeniden yayınlama işlemi creator tarafından yapılamaz.",
    "reason": "Neden"
  },
  "de": {
    "mine": "Meine Erlebnisse",
    "active": "Aktiv",
    "views": "Aufrufe",
    "engagement": "Interaktionen",
    "completions": "Abschlüsse",
    "allExperiences": "Alle Erlebnisse",
    "search": "Erlebnisse suchen",
    "statusFilter": "Status filtern",
    "allStatuses": "Alle Status",
    "paused": "Pausiert",
    "draft": "Entwurf",
    "sort": "Erlebnisse sortieren",
    "newest": "Neueste",
    "oldest": "Älteste",
    "mostViewed": "Meiste Aufrufe",
    "mostEngaged": "Meiste Interaktionen",
    "mostCompleted": "Meiste Abschlüsse",
    "loading": "Erlebnisse werden geladen…",
    "status": "Status",
    "lastActivity": "Letzte Aktivität",
    "noResults": "Keine Ergebnisse",
    "changeFilters": "Ändere deine Suche oder Filter.",
    "experiences": "Erlebnisse",
    "starts": "Starts",
    "responses": "Antworten",
    "moderation": "Moderation",
    "archived": "Archiviert",
    "noActivity": "Noch keine",
    "publishedOn": "Veröffentlicht am {date}",
    "unknown": "Unbekannt",
    "story": "Geschichte / Inhalt",
    "questionConfession": "Frage oder Geständnis?",
    "compatibility": "Liebesbarometer",
    "guess": "Raten / Was ist das?",
    "recommendation": "Empfehlung",
    "decision": "Meinung & Entscheidung",
    "guided": "Geführt",
    "score": "Richtige Antwort / Punkte",
    "spectrum": "Wie viel X bist du?",
    "archetype": "Welcher X bist du?",
    "emptyTitle": "Noch keine Erlebnisse",
    "emptyHint": "Dein erstes veröffentlichtes Erlebnis erscheint hier.",
    "newExperience": "Neues Erlebnis",
    "view": "Ansehen ↗",
    "edit": "Inhalt bearbeiten",
    "opening": "Inhalt wird geöffnet…",
    "updating": "Wird aktualisiert…",
    "pause": "Pausieren",
    "republish": "Erneut veröffentlichen",
    "closeShare": "Teilen schließen",
    "share": "Teilen",
    "copyLink": "Link kopieren",
    "copied": "Kopiert ✓",
    "shareOnX": "Auf X teilen",
    "participants": "Teilnehmende",
    "loadingParticipants": "Teilnehmende werden geladen…",
    "noParticipants": "Noch keine Abschlüsse.",
    "anonymous": "Anonym",
    "result": "Ergebnis",
    "completed": "Abgeschlossen",
    "correct": "Richtig",
    "answers": "Gegebene Antworten",
    "question": "Frage",
    "option": "Option",
    "participantAnswer": "Antwort der teilnehmenden Person",
    "shareHeading": "Teile dein Erlebnis.",
    "shareHint": "Kopiere den Link oder teile ihn in sozialen Netzwerken.",
    "qrCode": "QR-Code",
    "qrAlt": "QR-Code des Erlebnisses",
    "qrHint": "Nutze ihn vor Ort oder auf einem anderen Bild.",
    "openQr": "QR öffnen ↗",
    "participantsHint": "Die neuesten Abschlüsse erscheinen zuerst.",
    "storyNoData": "Dieses Erlebnis erfasst keine Fragen und Antworten.",
    "guessNoData": "Raten abgeschlossen. Die Freitextantwort wird hier nicht gespeichert.",
    "completionNoData": "Keine Antwortdetails zu diesem Abschluss.",
    "moderationLock": "Moderationssperre",
    "moderationPaused": "AQRYO hat dieses Erlebnis durch Moderation pausiert.",
    "cannotRepublish": "Creator können es nicht erneut veröffentlichen.",
    "reason": "Grund"
  },
  "ru": {
    "mine": "Мои материалы",
    "active": "Активно",
    "views": "Просмотры",
    "engagement": "Взаимодействия",
    "completions": "Завершения",
    "allExperiences": "Все материалы",
    "search": "Поиск материалов",
    "statusFilter": "Фильтр статуса",
    "allStatuses": "Все статусы",
    "paused": "Приостановлено",
    "draft": "Черновик",
    "sort": "Сортировка",
    "newest": "Сначала новые",
    "oldest": "Сначала старые",
    "mostViewed": "Больше просмотров",
    "mostEngaged": "Больше взаимодействий",
    "mostCompleted": "Больше завершений",
    "loading": "Загрузка материалов…",
    "status": "Статус",
    "lastActivity": "Последняя активность",
    "noResults": "Ничего не найдено",
    "changeFilters": "Измените запрос или фильтры.",
    "experiences": "Материалы",
    "starts": "Начали",
    "responses": "Ответы",
    "moderation": "Модерация",
    "archived": "В архиве",
    "noActivity": "Пока нет",
    "publishedOn": "Опубликовано {date}",
    "unknown": "Неизвестно",
    "story": "История / Контент",
    "questionConfession": "Вопрос или признание?",
    "compatibility": "Совместимость",
    "guess": "Угадай / Что это?",
    "recommendation": "Рекомендация",
    "decision": "Мнение и решение",
    "guided": "С подсказками",
    "score": "Верный ответ / Баллы",
    "spectrum": "Насколько вы X?",
    "archetype": "Какой вы X?",
    "emptyTitle": "Пока нет материалов",
    "emptyHint": "Ваш первый опубликованный материал появится здесь.",
    "newExperience": "Новый материал",
    "view": "Открыть ↗",
    "edit": "Редактировать",
    "opening": "Открываем материал…",
    "updating": "Обновляем…",
    "pause": "Приостановить",
    "republish": "Опубликовать снова",
    "closeShare": "Закрыть меню",
    "share": "Поделиться",
    "copyLink": "Копировать ссылку",
    "copied": "Скопировано ✓",
    "shareOnX": "Поделиться в X",
    "participants": "Участники",
    "loadingParticipants": "Загрузка участников…",
    "noParticipants": "Пока никто не завершил.",
    "anonymous": "Аноним",
    "result": "Результат",
    "completed": "Завершено",
    "correct": "Верно",
    "answers": "Полученные ответы",
    "question": "Вопрос",
    "option": "Вариант",
    "participantAnswer": "Ответ участника",
    "shareHeading": "Поделитесь своим материалом.",
    "shareHint": "Скопируйте ссылку или поделитесь в социальных сетях.",
    "qrCode": "QR-код",
    "qrAlt": "QR-код материала",
    "qrHint": "Используйте его офлайн или на другом изображении.",
    "openQr": "Открыть QR ↗",
    "participantsHint": "Сначала показаны последние завершения.",
    "storyNoData": "Этот материал не собирает вопросы и ответы.",
    "guessNoData": "Угадывание завершено. Текст ответа не сохранён в этой записи.",
    "completionNoData": "Подробностей ответов для этого завершения нет.",
    "moderationLock": "Блокировка модерации",
    "moderationPaused": "Модерация AQRYO приостановила этот материал.",
    "cannotRepublish": "Автор не может опубликовать его повторно.",
    "reason": "Причина"
  },
  "es": {
    "mine": "Mis experiencias",
    "active": "Activo",
    "views": "Vistas",
    "engagement": "Interacciones",
    "completions": "Finalizaciones",
    "allExperiences": "Todas las experiencias",
    "search": "Buscar experiencias",
    "statusFilter": "Filtrar estado",
    "allStatuses": "Todos los estados",
    "paused": "Pausado",
    "draft": "Borrador",
    "sort": "Ordenar experiencias",
    "newest": "Más recientes",
    "oldest": "Más antiguas",
    "mostViewed": "Más vistas",
    "mostEngaged": "Más interacción",
    "mostCompleted": "Más finalizaciones",
    "loading": "Cargando experiencias…",
    "status": "Estado",
    "lastActivity": "Última actividad",
    "noResults": "Sin resultados",
    "changeFilters": "Cambia la búsqueda o los filtros.",
    "experiences": "Experiencias",
    "starts": "Inicios",
    "responses": "Respuestas",
    "moderation": "Moderación",
    "archived": "Archivado",
    "noActivity": "Todavía no",
    "publishedOn": "Publicado el {date}",
    "unknown": "Desconocido",
    "story": "Historia / Contenido",
    "questionConfession": "¿Pregunta o confesión?",
    "compatibility": "Compatibilidad",
    "guess": "Adivina / ¿Qué es?",
    "recommendation": "Recomendación",
    "decision": "Opinión y decisión",
    "guided": "Guiado",
    "score": "Respuesta correcta / Puntuación",
    "spectrum": "¿Cuánto X eres?",
    "archetype": "¿Qué X eres?",
    "emptyTitle": "Aún no hay experiencias",
    "emptyHint": "Tu primera experiencia publicada aparecerá aquí.",
    "newExperience": "Nueva experiencia",
    "view": "Ver ↗",
    "edit": "Editar contenido",
    "opening": "Abriendo contenido…",
    "updating": "Actualizando…",
    "pause": "Pausar",
    "republish": "Volver a publicar",
    "closeShare": "Cerrar opciones",
    "share": "Compartir",
    "copyLink": "Copiar enlace",
    "copied": "Copiado ✓",
    "shareOnX": "Compartir en X",
    "participants": "Participantes",
    "loadingParticipants": "Cargando participantes…",
    "noParticipants": "Aún no hay finalizaciones.",
    "anonymous": "Anónimo",
    "result": "Resultado",
    "completed": "Completado",
    "correct": "Correcto",
    "answers": "Respuestas dadas",
    "question": "Pregunta",
    "option": "Opción",
    "participantAnswer": "Respuesta del participante",
    "shareHeading": "Comparte tu experiencia.",
    "shareHint": "Copia el enlace o compártelo en redes sociales.",
    "qrCode": "Código QR",
    "qrAlt": "Código QR de la experiencia",
    "qrHint": "Úsalo en espacios físicos o sobre otra imagen.",
    "openQr": "Abrir QR ↗",
    "participantsHint": "Las finalizaciones más recientes aparecen primero.",
    "storyNoData": "Esta experiencia no recoge preguntas y respuestas.",
    "guessNoData": "La adivinanza terminó. El texto libre no se guarda en este registro.",
    "completionNoData": "No hay detalles de respuestas para esta finalización.",
    "moderationLock": "Bloqueo de moderación",
    "moderationPaused": "La moderación de AQRYO pausó esta experiencia.",
    "cannotRepublish": "El creador no puede volver a publicarla.",
    "reason": "Motivo"
  },
  "pt": {
    "mine": "Minhas experiências",
    "active": "Ativo",
    "views": "Visualizações",
    "engagement": "Interações",
    "completions": "Conclusões",
    "allExperiences": "Todas as experiências",
    "search": "Buscar experiências",
    "statusFilter": "Filtrar status",
    "allStatuses": "Todos os status",
    "paused": "Pausado",
    "draft": "Rascunho",
    "sort": "Ordenar experiências",
    "newest": "Mais recentes",
    "oldest": "Mais antigas",
    "mostViewed": "Mais visualizações",
    "mostEngaged": "Mais interação",
    "mostCompleted": "Mais conclusões",
    "loading": "Carregando experiências…",
    "status": "Status",
    "lastActivity": "Última atividade",
    "noResults": "Nenhum resultado",
    "changeFilters": "Altere a busca ou os filtros.",
    "experiences": "Experiências",
    "starts": "Inícios",
    "responses": "Respostas",
    "moderation": "Moderação",
    "archived": "Arquivado",
    "noActivity": "Ainda não",
    "publishedOn": "Publicado em {date}",
    "unknown": "Desconhecido",
    "story": "História / Conteúdo",
    "questionConfession": "Pergunta ou confissão?",
    "compatibility": "Compatibilidade",
    "guess": "Adivinhe / O que é?",
    "recommendation": "Recomendação",
    "decision": "Opinião e decisão",
    "guided": "Guiado",
    "score": "Resposta correta / Pontuação",
    "spectrum": "Quanto X você é?",
    "archetype": "Qual X você é?",
    "emptyTitle": "Ainda não há experiências",
    "emptyHint": "Sua primeira experiência publicada aparecerá aqui.",
    "newExperience": "Nova experiência",
    "view": "Ver ↗",
    "edit": "Editar conteúdo",
    "opening": "Abrindo conteúdo…",
    "updating": "Atualizando…",
    "pause": "Pausar",
    "republish": "Publicar novamente",
    "closeShare": "Fechar opções",
    "share": "Compartilhar",
    "copyLink": "Copiar link",
    "copied": "Copiado ✓",
    "shareOnX": "Compartilhar no X",
    "participants": "Participantes",
    "loadingParticipants": "Carregando participantes…",
    "noParticipants": "Ainda não há conclusões.",
    "anonymous": "Anônimo",
    "result": "Resultado",
    "completed": "Concluído",
    "correct": "Correto",
    "answers": "Respostas dadas",
    "question": "Pergunta",
    "option": "Opção",
    "participantAnswer": "Resposta do participante",
    "shareHeading": "Compartilhe sua experiência.",
    "shareHint": "Copie o link ou compartilhe nas redes sociais.",
    "qrCode": "Código QR",
    "qrAlt": "Código QR da experiência",
    "qrHint": "Use em espaços físicos ou sobre outra imagem.",
    "openQr": "Abrir QR ↗",
    "participantsHint": "As conclusões mais recentes aparecem primeiro.",
    "storyNoData": "Esta experiência não coleta perguntas e respostas.",
    "guessNoData": "A adivinhação terminou. O texto livre não é salvo neste registro.",
    "completionNoData": "Não há detalhes de respostas para esta conclusão.",
    "moderationLock": "Bloqueio de moderação",
    "moderationPaused": "A moderação do AQRYO pausou esta experiência.",
    "cannotRepublish": "O criador não pode publicá-la novamente.",
    "reason": "Motivo"
  },
  "fr": {
    "mine": "Mes expériences",
    "active": "Actif",
    "views": "Vues",
    "engagement": "Interactions",
    "completions": "Finalisations",
    "allExperiences": "Toutes les expériences",
    "search": "Rechercher des expériences",
    "statusFilter": "Filtrer le statut",
    "allStatuses": "Tous les statuts",
    "paused": "En pause",
    "draft": "Brouillon",
    "sort": "Trier les expériences",
    "newest": "Plus récentes",
    "oldest": "Plus anciennes",
    "mostViewed": "Plus de vues",
    "mostEngaged": "Plus d’interactions",
    "mostCompleted": "Plus de finalisations",
    "loading": "Chargement des expériences…",
    "status": "Statut",
    "lastActivity": "Dernière activité",
    "noResults": "Aucun résultat",
    "changeFilters": "Modifiez la recherche ou les filtres.",
    "experiences": "Expériences",
    "starts": "Démarrages",
    "responses": "Réponses",
    "moderation": "Modération",
    "archived": "Archivé",
    "noActivity": "Pas encore",
    "publishedOn": "Publié le {date}",
    "unknown": "Inconnu",
    "story": "Histoire / Contenu",
    "questionConfession": "Question ou confession ?",
    "compatibility": "Compatibilité",
    "guess": "Devinez / Qu’est-ce que c’est ?",
    "recommendation": "Recommandation",
    "decision": "Opinion et décision",
    "guided": "Guidé",
    "score": "Bonne réponse / Score",
    "spectrum": "À quel point êtes-vous X ?",
    "archetype": "Quel X êtes-vous ?",
    "emptyTitle": "Aucune expérience pour le moment",
    "emptyHint": "Votre première expérience publiée apparaîtra ici.",
    "newExperience": "Nouvelle expérience",
    "view": "Voir ↗",
    "edit": "Modifier le contenu",
    "opening": "Ouverture du contenu…",
    "updating": "Mise à jour…",
    "pause": "Mettre en pause",
    "republish": "Publier à nouveau",
    "closeShare": "Fermer le partage",
    "share": "Partager",
    "copyLink": "Copier le lien",
    "copied": "Copié ✓",
    "shareOnX": "Partager sur X",
    "participants": "Participants",
    "loadingParticipants": "Chargement des participants…",
    "noParticipants": "Aucune finalisation pour le moment.",
    "anonymous": "Anonyme",
    "result": "Résultat",
    "completed": "Terminé",
    "correct": "Correct",
    "answers": "Réponses données",
    "question": "Question",
    "option": "Option",
    "participantAnswer": "Réponse du participant",
    "shareHeading": "Partagez votre expérience.",
    "shareHint": "Copiez le lien ou partagez-le sur les réseaux sociaux.",
    "qrCode": "Code QR",
    "qrAlt": "Code QR de l’expérience",
    "qrHint": "Utilisez-le dans un lieu physique ou sur une autre image.",
    "openQr": "Ouvrir le QR ↗",
    "participantsHint": "Les finalisations les plus récentes apparaissent en premier.",
    "storyNoData": "Cette expérience ne collecte pas de questions et réponses.",
    "guessNoData": "La devinette est terminée. Le texte libre n’est pas conservé ici.",
    "completionNoData": "Aucun détail de réponse pour cette finalisation.",
    "moderationLock": "Blocage de modération",
    "moderationPaused": "La modération AQRYO a mis cette expérience en pause.",
    "cannotRepublish": "Le créateur ne peut pas la republier.",
    "reason": "Motif"
  },
  "it": {
    "mine": "Le mie esperienze",
    "active": "Attivo",
    "views": "Visualizzazioni",
    "engagement": "Interazioni",
    "completions": "Completamenti",
    "allExperiences": "Tutte le esperienze",
    "search": "Cerca esperienze",
    "statusFilter": "Filtra stato",
    "allStatuses": "Tutti gli stati",
    "paused": "In pausa",
    "draft": "Bozza",
    "sort": "Ordina esperienze",
    "newest": "Più recenti",
    "oldest": "Meno recenti",
    "mostViewed": "Più visualizzazioni",
    "mostEngaged": "Più interazioni",
    "mostCompleted": "Più completamenti",
    "loading": "Caricamento esperienze…",
    "status": "Stato",
    "lastActivity": "Ultima attività",
    "noResults": "Nessun risultato",
    "changeFilters": "Modifica la ricerca o i filtri.",
    "experiences": "Esperienze",
    "starts": "Avvii",
    "responses": "Risposte",
    "moderation": "Moderazione",
    "archived": "Archiviato",
    "noActivity": "Non ancora",
    "publishedOn": "Pubblicato il {date}",
    "unknown": "Sconosciuto",
    "story": "Storia / Contenuto",
    "questionConfession": "Domanda o confessione?",
    "compatibility": "Compatibilità",
    "guess": "Indovina / Che cos’è?",
    "recommendation": "Raccomandazione",
    "decision": "Opinione e decisione",
    "guided": "Guidato",
    "score": "Risposta corretta / Punteggio",
    "spectrum": "Quanto sei X?",
    "archetype": "Quale X sei?",
    "emptyTitle": "Nessuna esperienza ancora",
    "emptyHint": "La tua prima esperienza pubblicata apparirà qui.",
    "newExperience": "Nuova esperienza",
    "view": "Visualizza ↗",
    "edit": "Modifica contenuto",
    "opening": "Apertura contenuto…",
    "updating": "Aggiornamento…",
    "pause": "Metti in pausa",
    "republish": "Ripubblica",
    "closeShare": "Chiudi condivisione",
    "share": "Condividi",
    "copyLink": "Copia link",
    "copied": "Copiato ✓",
    "shareOnX": "Condividi su X",
    "participants": "Partecipanti",
    "loadingParticipants": "Caricamento partecipanti…",
    "noParticipants": "Nessun completamento ancora.",
    "anonymous": "Anonimo",
    "result": "Risultato",
    "completed": "Completato",
    "correct": "Corretto",
    "answers": "Risposte date",
    "question": "Domanda",
    "option": "Opzione",
    "participantAnswer": "Risposta del partecipante",
    "shareHeading": "Condividi la tua esperienza.",
    "shareHint": "Copia il link o condividilo sui social.",
    "qrCode": "Codice QR",
    "qrAlt": "Codice QR dell’esperienza",
    "qrHint": "Usalo in luoghi fisici o su un’altra immagine.",
    "openQr": "Apri QR ↗",
    "participantsHint": "I completamenti più recenti appaiono per primi.",
    "storyNoData": "Questa esperienza non raccoglie domande e risposte.",
    "guessNoData": "Il gioco è completato. Il testo libero non viene salvato qui.",
    "completionNoData": "Nessun dettaglio delle risposte per questo completamento.",
    "moderationLock": "Blocco di moderazione",
    "moderationPaused": "La moderazione AQRYO ha sospeso questa esperienza.",
    "cannotRepublish": "Il creatore non può ripubblicarla.",
    "reason": "Motivo"
  },
  "ar": {
    "mine": "محتواي",
    "active": "نشط",
    "views": "المشاهدات",
    "engagement": "التفاعلات",
    "completions": "الإكمالات",
    "allExperiences": "كل المحتوى",
    "search": "البحث في المحتوى",
    "statusFilter": "تصفية الحالة",
    "allStatuses": "كل الحالات",
    "paused": "متوقف",
    "draft": "مسودة",
    "sort": "ترتيب المحتوى",
    "newest": "الأحدث",
    "oldest": "الأقدم",
    "mostViewed": "الأكثر مشاهدة",
    "mostEngaged": "الأكثر تفاعلاً",
    "mostCompleted": "الأكثر إكمالاً",
    "loading": "جارٍ تحميل المحتوى…",
    "status": "الحالة",
    "lastActivity": "آخر نشاط",
    "noResults": "لا توجد نتائج",
    "changeFilters": "غيّر البحث أو عوامل التصفية.",
    "experiences": "المحتوى",
    "starts": "مرات البدء",
    "responses": "الردود",
    "moderation": "المراجعة",
    "archived": "مؤرشف",
    "noActivity": "لا يوجد بعد",
    "publishedOn": "نُشر في {date}",
    "unknown": "غير معروف",
    "story": "قصة / محتوى",
    "questionConfession": "سؤال أم اعتراف؟",
    "compatibility": "مقياس التوافق",
    "guess": "خمّن / ما هذا؟",
    "recommendation": "توصية",
    "decision": "رأي وقرار",
    "guided": "موجّه",
    "score": "الإجابة الصحيحة / النقاط",
    "spectrum": "إلى أي مدى أنت X؟",
    "archetype": "أي X أنت؟",
    "emptyTitle": "لا يوجد محتوى بعد",
    "emptyHint": "سيظهر أول محتوى تنشره هنا.",
    "newExperience": "محتوى جديد",
    "view": "عرض ↗",
    "edit": "تعديل المحتوى",
    "opening": "جارٍ فتح المحتوى…",
    "updating": "جارٍ التحديث…",
    "pause": "إيقاف مؤقت",
    "republish": "إعادة النشر",
    "closeShare": "إغلاق المشاركة",
    "share": "مشاركة",
    "copyLink": "نسخ الرابط",
    "copied": "تم النسخ ✓",
    "shareOnX": "مشاركة على X",
    "participants": "المشاركون",
    "loadingParticipants": "جارٍ تحميل المشاركين…",
    "noParticipants": "لم يكمل أحد بعد.",
    "anonymous": "مجهول",
    "result": "النتيجة",
    "completed": "مكتمل",
    "correct": "صحيح",
    "answers": "الإجابات المقدمة",
    "question": "سؤال",
    "option": "خيار",
    "participantAnswer": "إجابة المشارك",
    "shareHeading": "شارك محتواك.",
    "shareHint": "انسخ الرابط أو شاركه على الشبكات الاجتماعية.",
    "qrCode": "رمز QR",
    "qrAlt": "رمز QR للمحتوى",
    "qrHint": "استخدمه في أماكن فعلية أو على صورة أخرى.",
    "openQr": "فتح QR ↗",
    "participantsHint": "تظهر أحدث الإكمالات أولاً.",
    "storyNoData": "لا يجمع هذا المحتوى بيانات الأسئلة والأجوبة.",
    "guessNoData": "اكتمل التخمين. لا يُحفظ نص الإجابة الحرة في هذا السجل.",
    "completionNoData": "لا توجد تفاصيل إجابات لهذا الإكمال.",
    "moderationLock": "قفل المراجعة",
    "moderationPaused": "أوقفت مراجعة AQRYO هذا المحتوى.",
    "cannotRepublish": "لا يمكن لصانع المحتوى إعادة نشره.",
    "reason": "السبب"
  },
  "hi": {
    "mine": "मेरी सामग्री",
    "active": "सक्रिय",
    "views": "दृश्य",
    "engagement": "सहभागिता",
    "completions": "पूर्णताएँ",
    "allExperiences": "सभी सामग्री",
    "search": "सामग्री खोजें",
    "statusFilter": "स्थिति फ़िल्टर",
    "allStatuses": "सभी स्थितियाँ",
    "paused": "रुका हुआ",
    "draft": "ड्राफ़्ट",
    "sort": "सामग्री क्रम",
    "newest": "सबसे नया",
    "oldest": "सबसे पुराना",
    "mostViewed": "सबसे अधिक दृश्य",
    "mostEngaged": "सबसे अधिक सहभागिता",
    "mostCompleted": "सबसे अधिक पूर्णताएँ",
    "loading": "सामग्री लोड हो रही है…",
    "status": "स्थिति",
    "lastActivity": "अंतिम गतिविधि",
    "noResults": "कोई परिणाम नहीं",
    "changeFilters": "खोज या फ़िल्टर बदलें।",
    "experiences": "सामग्री",
    "starts": "शुरुआत",
    "responses": "उत्तर",
    "moderation": "मॉडरेशन",
    "archived": "संग्रहीत",
    "noActivity": "अभी नहीं",
    "publishedOn": "{date} को प्रकाशित",
    "unknown": "अज्ञात",
    "story": "कहानी / सामग्री",
    "questionConfession": "सवाल या कबूलनामा?",
    "compatibility": "अनुकूलता",
    "guess": "अंदाज़ा लगाएँ / यह क्या है?",
    "recommendation": "सुझाव",
    "decision": "राय और निर्णय",
    "guided": "निर्देशित",
    "score": "सही उत्तर / स्कोर",
    "spectrum": "आप कितने X हैं?",
    "archetype": "आप कौन से X हैं?",
    "emptyTitle": "अभी कोई सामग्री नहीं",
    "emptyHint": "आपकी पहली प्रकाशित सामग्री यहाँ दिखेगी।",
    "newExperience": "नई सामग्री",
    "view": "देखें ↗",
    "edit": "सामग्री संपादित करें",
    "opening": "सामग्री खुल रही है…",
    "updating": "अपडेट हो रहा है…",
    "pause": "रोकें",
    "republish": "दोबारा प्रकाशित करें",
    "closeShare": "साझा विकल्प बंद करें",
    "share": "साझा करें",
    "copyLink": "लिंक कॉपी करें",
    "copied": "कॉपी हुआ ✓",
    "shareOnX": "X पर साझा करें",
    "participants": "प्रतिभागी",
    "loadingParticipants": "प्रतिभागी लोड हो रहे हैं…",
    "noParticipants": "अभी किसी ने पूरा नहीं किया।",
    "anonymous": "गुमनाम",
    "result": "परिणाम",
    "completed": "पूरा हुआ",
    "correct": "सही",
    "answers": "दिए गए उत्तर",
    "question": "प्रश्न",
    "option": "विकल्प",
    "participantAnswer": "प्रतिभागी का उत्तर",
    "shareHeading": "अपनी सामग्री साझा करें।",
    "shareHint": "लिंक कॉपी करें या सोशल मीडिया पर साझा करें।",
    "qrCode": "QR कोड",
    "qrAlt": "सामग्री का QR कोड",
    "qrHint": "इसे भौतिक स्थानों या दूसरी तस्वीर पर इस्तेमाल करें।",
    "openQr": "QR खोलें ↗",
    "participantsHint": "नवीनतम पूर्णताएँ पहले दिखाई जाती हैं।",
    "storyNoData": "यह सामग्री प्रश्न और उत्तर के डेटा नहीं लेती।",
    "guessNoData": "अनुमान पूरा हुआ। मुक्त पाठ का उत्तर इस रिकॉर्ड में नहीं रखा गया।",
    "completionNoData": "इस पूर्णता के उत्तर का विवरण नहीं है।",
    "moderationLock": "मॉडरेशन लॉक",
    "moderationPaused": "AQRYO मॉडरेशन ने यह सामग्री रोक दी है।",
    "cannotRepublish": "निर्माता इसे दोबारा प्रकाशित नहीं कर सकते।",
    "reason": "कारण"
  },
  "id": {
    "mine": "Pengalaman saya",
    "active": "Aktif",
    "views": "Tayangan",
    "engagement": "Interaksi",
    "completions": "Penyelesaian",
    "allExperiences": "Semua pengalaman",
    "search": "Cari pengalaman",
    "statusFilter": "Filter status",
    "allStatuses": "Semua status",
    "paused": "Dijeda",
    "draft": "Draf",
    "sort": "Urutkan pengalaman",
    "newest": "Terbaru",
    "oldest": "Terlama",
    "mostViewed": "Paling banyak dilihat",
    "mostEngaged": "Interaksi terbanyak",
    "mostCompleted": "Penyelesaian terbanyak",
    "loading": "Memuat pengalaman…",
    "status": "Status",
    "lastActivity": "Aktivitas terakhir",
    "noResults": "Tidak ada hasil",
    "changeFilters": "Ubah pencarian atau filter.",
    "experiences": "Pengalaman",
    "starts": "Mulai",
    "responses": "Respons",
    "moderation": "Moderasi",
    "archived": "Diarsipkan",
    "noActivity": "Belum ada",
    "publishedOn": "Diterbitkan {date}",
    "unknown": "Tidak diketahui",
    "story": "Cerita / Konten",
    "questionConfession": "Pertanyaan atau pengakuan?",
    "compatibility": "Kecocokan",
    "guess": "Tebak / Apa ini?",
    "recommendation": "Rekomendasi",
    "decision": "Pendapat dan keputusan",
    "guided": "Terpandu",
    "score": "Jawaban benar / Skor",
    "spectrum": "Seberapa X kamu?",
    "archetype": "X yang mana kamu?",
    "emptyTitle": "Belum ada pengalaman",
    "emptyHint": "Pengalaman pertama yang diterbitkan akan muncul di sini.",
    "newExperience": "Pengalaman baru",
    "view": "Lihat ↗",
    "edit": "Edit konten",
    "opening": "Membuka konten…",
    "updating": "Memperbarui…",
    "pause": "Jeda",
    "republish": "Terbitkan ulang",
    "closeShare": "Tutup berbagi",
    "share": "Bagikan",
    "copyLink": "Salin tautan",
    "copied": "Disalin ✓",
    "shareOnX": "Bagikan di X",
    "participants": "Peserta",
    "loadingParticipants": "Memuat peserta…",
    "noParticipants": "Belum ada yang menyelesaikan.",
    "anonymous": "Anonim",
    "result": "Hasil",
    "completed": "Selesai",
    "correct": "Benar",
    "answers": "Jawaban yang diberikan",
    "question": "Pertanyaan",
    "option": "Pilihan",
    "participantAnswer": "Jawaban peserta",
    "shareHeading": "Bagikan pengalamanmu.",
    "shareHint": "Salin tautan atau bagikan di media sosial.",
    "qrCode": "Kode QR",
    "qrAlt": "Kode QR pengalaman",
    "qrHint": "Gunakan di lokasi fisik atau pada gambar lain.",
    "openQr": "Buka QR ↗",
    "participantsHint": "Penyelesaian terbaru ditampilkan lebih dahulu.",
    "storyNoData": "Pengalaman ini tidak mengumpulkan data tanya jawab.",
    "guessNoData": "Tebakan selesai. Jawaban teks bebas tidak disimpan di catatan ini.",
    "completionNoData": "Tidak ada detail jawaban untuk penyelesaian ini.",
    "moderationLock": "Kunci moderasi",
    "moderationPaused": "Moderasi AQRYO telah menjeda pengalaman ini.",
    "cannotRepublish": "Kreator tidak dapat menerbitkannya ulang.",
    "reason": "Alasan"
  },
  "bn": {
    "mine": "আমার কনটেন্ট",
    "active": "সক্রিয়",
    "views": "দেখা হয়েছে",
    "engagement": "অংশগ্রহণ",
    "completions": "সমাপ্তি",
    "allExperiences": "সব কনটেন্ট",
    "search": "কনটেন্ট খুঁজুন",
    "statusFilter": "স্ট্যাটাস ফিল্টার",
    "allStatuses": "সব স্ট্যাটাস",
    "paused": "বিরত",
    "draft": "খসড়া",
    "sort": "কনটেন্ট সাজান",
    "newest": "নতুন আগে",
    "oldest": "পুরোনো আগে",
    "mostViewed": "সর্বাধিক দেখা",
    "mostEngaged": "সর্বাধিক অংশগ্রহণ",
    "mostCompleted": "সর্বাধিক সমাপ্তি",
    "loading": "কনটেন্ট লোড হচ্ছে…",
    "status": "স্ট্যাটাস",
    "lastActivity": "সর্বশেষ কার্যকলাপ",
    "noResults": "কোনো ফলাফল নেই",
    "changeFilters": "অনুসন্ধান বা ফিল্টার বদলান।",
    "experiences": "কনটেন্ট",
    "starts": "শুরু",
    "responses": "উত্তর",
    "moderation": "মডারেশন",
    "archived": "আর্কাইভ করা",
    "noActivity": "এখনও নেই",
    "publishedOn": "{date} প্রকাশিত",
    "unknown": "অজানা",
    "story": "গল্প / কনটেন্ট",
    "questionConfession": "প্রশ্ন নাকি স্বীকারোক্তি?",
    "compatibility": "সামঞ্জস্য",
    "guess": "অনুমান করুন / এটি কী?",
    "recommendation": "সুপারিশ",
    "decision": "মতামত ও সিদ্ধান্ত",
    "guided": "নির্দেশিত",
    "score": "সঠিক উত্তর / স্কোর",
    "spectrum": "আপনি কতটা X?",
    "archetype": "আপনি কোন X?",
    "emptyTitle": "এখনও কোনো কনটেন্ট নেই",
    "emptyHint": "আপনার প্রথম প্রকাশিত কনটেন্ট এখানে দেখা যাবে।",
    "newExperience": "নতুন কনটেন্ট",
    "view": "দেখুন ↗",
    "edit": "কনটেন্ট সম্পাদনা",
    "opening": "কনটেন্ট খুলছে…",
    "updating": "আপডেট হচ্ছে…",
    "pause": "বিরতি দিন",
    "republish": "আবার প্রকাশ করুন",
    "closeShare": "শেয়ার বন্ধ করুন",
    "share": "শেয়ার করুন",
    "copyLink": "লিংক কপি করুন",
    "copied": "কপি হয়েছে ✓",
    "shareOnX": "X-এ শেয়ার করুন",
    "participants": "অংশগ্রহণকারী",
    "loadingParticipants": "অংশগ্রহণকারী লোড হচ্ছে…",
    "noParticipants": "এখনও কেউ শেষ করেনি।",
    "anonymous": "বেনামি",
    "result": "ফলাফল",
    "completed": "সম্পন্ন",
    "correct": "সঠিক",
    "answers": "দেওয়া উত্তর",
    "question": "প্রশ্ন",
    "option": "বিকল্প",
    "participantAnswer": "অংশগ্রহণকারীর উত্তর",
    "shareHeading": "আপনার কনটেন্ট শেয়ার করুন।",
    "shareHint": "লিংক কপি করুন বা সামাজিক মাধ্যমে শেয়ার করুন।",
    "qrCode": "QR কোড",
    "qrAlt": "কনটেন্টের QR কোড",
    "qrHint": "বাস্তব স্থানে বা অন্য ছবিতে ব্যবহার করুন।",
    "openQr": "QR খুলুন ↗",
    "participantsHint": "সর্বশেষ সমাপ্তি আগে দেখানো হয়।",
    "storyNoData": "এই কনটেন্ট প্রশ্নোত্তরের তথ্য সংগ্রহ করে না।",
    "guessNoData": "অনুমান শেষ হয়েছে। মুক্ত পাঠের উত্তর এই রেকর্ডে রাখা হয়নি।",
    "completionNoData": "এই সমাপ্তির উত্তরের বিবরণ নেই।",
    "moderationLock": "মডারেশন লক",
    "moderationPaused": "AQRYO মডারেশন এই কনটেন্ট বিরত করেছে।",
    "cannotRepublish": "নির্মাতা এটি আবার প্রকাশ করতে পারবেন না।",
    "reason": "কারণ"
  },
  "ur": {
    "mine": "میرا مواد",
    "active": "فعال",
    "views": "ملاحظات",
    "engagement": "تعامل",
    "completions": "تکمیل",
    "allExperiences": "تمام مواد",
    "search": "مواد تلاش کریں",
    "statusFilter": "حالت کا فلٹر",
    "allStatuses": "تمام حالتیں",
    "paused": "روکا گیا",
    "draft": "مسودہ",
    "sort": "مواد کی ترتیب",
    "newest": "تازہ ترین",
    "oldest": "قدیم ترین",
    "mostViewed": "سب سے زیادہ دیکھا گیا",
    "mostEngaged": "سب سے زیادہ تعامل",
    "mostCompleted": "سب سے زیادہ تکمیل",
    "loading": "مواد لوڈ ہو رہا ہے…",
    "status": "حالت",
    "lastActivity": "آخری سرگرمی",
    "noResults": "کوئی نتیجہ نہیں",
    "changeFilters": "تلاش یا فلٹر تبدیل کریں۔",
    "experiences": "مواد",
    "starts": "آغاز",
    "responses": "جوابات",
    "moderation": "نگرانی",
    "archived": "محفوظ شدہ",
    "noActivity": "ابھی نہیں",
    "publishedOn": "{date} کو شائع ہوا",
    "unknown": "نامعلوم",
    "story": "کہانی / مواد",
    "questionConfession": "سوال یا اعتراف؟",
    "compatibility": "مطابقت",
    "guess": "اندازہ لگائیں / یہ کیا ہے؟",
    "recommendation": "تجویز",
    "decision": "رائے اور فیصلہ",
    "guided": "رہنمائی کے ساتھ",
    "score": "درست جواب / اسکور",
    "spectrum": "آپ کتنے X ہیں؟",
    "archetype": "آپ کون سے X ہیں؟",
    "emptyTitle": "ابھی کوئی مواد نہیں",
    "emptyHint": "آپ کا پہلا شائع شدہ مواد یہاں ظاہر ہوگا۔",
    "newExperience": "نیا مواد",
    "view": "دیکھیں ↗",
    "edit": "مواد میں ترمیم",
    "opening": "مواد کھل رہا ہے…",
    "updating": "اپ ڈیٹ ہو رہا ہے…",
    "pause": "روکیں",
    "republish": "دوبارہ شائع کریں",
    "closeShare": "شیئر بند کریں",
    "share": "شیئر کریں",
    "copyLink": "لنک کاپی کریں",
    "copied": "کاپی ہو گیا ✓",
    "shareOnX": "X پر شیئر کریں",
    "participants": "شرکا",
    "loadingParticipants": "شرکا لوڈ ہو رہے ہیں…",
    "noParticipants": "ابھی کسی نے مکمل نہیں کیا۔",
    "anonymous": "گمنام",
    "result": "نتیجہ",
    "completed": "مکمل",
    "correct": "درست",
    "answers": "دیے گئے جوابات",
    "question": "سوال",
    "option": "انتخاب",
    "participantAnswer": "شریک کا جواب",
    "shareHeading": "اپنا مواد شیئر کریں۔",
    "shareHint": "لنک کاپی کریں یا سوشل میڈیا پر شیئر کریں۔",
    "qrCode": "QR کوڈ",
    "qrAlt": "مواد کا QR کوڈ",
    "qrHint": "اسے حقیقی جگہوں یا دوسری تصویر پر استعمال کریں۔",
    "openQr": "QR کھولیں ↗",
    "participantsHint": "تازہ ترین تکمیل پہلے دکھائی جاتی ہے۔",
    "storyNoData": "یہ مواد سوال و جواب کا ڈیٹا جمع نہیں کرتا۔",
    "guessNoData": "اندازہ مکمل ہوا۔ آزاد متن کا جواب اس ریکارڈ میں محفوظ نہیں ہے۔",
    "completionNoData": "اس تکمیل کے جواب کی تفصیلات نہیں ہیں۔",
    "moderationLock": "نگرانی کی پابندی",
    "moderationPaused": "AQRYO کی نگرانی نے یہ مواد روک دیا ہے۔",
    "cannotRepublish": "تخلیق کار اسے دوبارہ شائع نہیں کر سکتے۔",
    "reason": "وجہ"
  },
  "vi": {
    "mine": "Nội dung của tôi",
    "active": "Đang hoạt động",
    "views": "Lượt xem",
    "engagement": "Tương tác",
    "completions": "Hoàn thành",
    "allExperiences": "Tất cả nội dung",
    "search": "Tìm nội dung",
    "statusFilter": "Lọc trạng thái",
    "allStatuses": "Tất cả trạng thái",
    "paused": "Tạm dừng",
    "draft": "Bản nháp",
    "sort": "Sắp xếp nội dung",
    "newest": "Mới nhất",
    "oldest": "Cũ nhất",
    "mostViewed": "Nhiều lượt xem nhất",
    "mostEngaged": "Nhiều tương tác nhất",
    "mostCompleted": "Nhiều lượt hoàn thành nhất",
    "loading": "Đang tải nội dung…",
    "status": "Trạng thái",
    "lastActivity": "Hoạt động gần nhất",
    "noResults": "Không có kết quả",
    "changeFilters": "Thay đổi tìm kiếm hoặc bộ lọc.",
    "experiences": "Nội dung",
    "starts": "Lượt bắt đầu",
    "responses": "Phản hồi",
    "moderation": "Kiểm duyệt",
    "archived": "Đã lưu trữ",
    "noActivity": "Chưa có",
    "publishedOn": "Đăng ngày {date}",
    "unknown": "Không rõ",
    "story": "Câu chuyện / Nội dung",
    "questionConfession": "Câu hỏi hay lời thú nhận?",
    "compatibility": "Độ tương hợp",
    "guess": "Đoán / Đây là gì?",
    "recommendation": "Gợi ý",
    "decision": "Ý kiến và quyết định",
    "guided": "Có hướng dẫn",
    "score": "Đáp án đúng / Điểm",
    "spectrum": "Bạn là X đến mức nào?",
    "archetype": "Bạn là X nào?",
    "emptyTitle": "Chưa có nội dung",
    "emptyHint": "Nội dung đầu tiên được đăng sẽ xuất hiện ở đây.",
    "newExperience": "Nội dung mới",
    "view": "Xem ↗",
    "edit": "Sửa nội dung",
    "opening": "Đang mở nội dung…",
    "updating": "Đang cập nhật…",
    "pause": "Tạm dừng",
    "republish": "Đăng lại",
    "closeShare": "Đóng chia sẻ",
    "share": "Chia sẻ",
    "copyLink": "Sao chép liên kết",
    "copied": "Đã sao chép ✓",
    "shareOnX": "Chia sẻ trên X",
    "participants": "Người tham gia",
    "loadingParticipants": "Đang tải người tham gia…",
    "noParticipants": "Chưa có ai hoàn thành.",
    "anonymous": "Ẩn danh",
    "result": "Kết quả",
    "completed": "Đã hoàn thành",
    "correct": "Đúng",
    "answers": "Câu trả lời đã gửi",
    "question": "Câu hỏi",
    "option": "Lựa chọn",
    "participantAnswer": "Câu trả lời của người tham gia",
    "shareHeading": "Chia sẻ nội dung của bạn.",
    "shareHint": "Sao chép liên kết hoặc chia sẻ trên mạng xã hội.",
    "qrCode": "Mã QR",
    "qrAlt": "Mã QR của nội dung",
    "qrHint": "Dùng ở địa điểm thực tế hoặc trên một hình ảnh khác.",
    "openQr": "Mở QR ↗",
    "participantsHint": "Các lượt hoàn thành mới nhất được hiển thị trước.",
    "storyNoData": "Nội dung này không thu thập dữ liệu hỏi đáp.",
    "guessNoData": "Đã hoàn thành lượt đoán. Câu trả lời tự do không được lưu trong bản ghi này.",
    "completionNoData": "Không có chi tiết câu trả lời cho lượt hoàn thành này.",
    "moderationLock": "Khóa kiểm duyệt",
    "moderationPaused": "Kiểm duyệt AQRYO đã tạm dừng nội dung này.",
    "cannotRepublish": "Người tạo không thể đăng lại.",
    "reason": "Lý do"
  },
  "fil": {
    "mine": "Mga karanasan ko",
    "active": "Aktibo",
    "views": "Mga pagtingin",
    "engagement": "Pakikilahok",
    "completions": "Mga pagkumpleto",
    "allExperiences": "Lahat ng karanasan",
    "search": "Maghanap ng karanasan",
    "statusFilter": "Salain ang status",
    "allStatuses": "Lahat ng status",
    "paused": "Nakahinto",
    "draft": "Draft",
    "sort": "Ayusin ang karanasan",
    "newest": "Pinakabago",
    "oldest": "Pinakaluma",
    "mostViewed": "Pinakamaraming pagtingin",
    "mostEngaged": "Pinakamaraming pakikilahok",
    "mostCompleted": "Pinakamaraming pagkumpleto",
    "loading": "Naglo-load ng mga karanasan…",
    "status": "Status",
    "lastActivity": "Huling aktibidad",
    "noResults": "Walang resulta",
    "changeFilters": "Baguhin ang paghahanap o mga filter.",
    "experiences": "Mga karanasan",
    "starts": "Mga pagsisimula",
    "responses": "Mga sagot",
    "moderation": "Moderasyon",
    "archived": "Naka-archive",
    "noActivity": "Wala pa",
    "publishedOn": "Inilathala noong {date}",
    "unknown": "Hindi alam",
    "story": "Kuwento / Nilalaman",
    "questionConfession": "Tanong o pagtatapat?",
    "compatibility": "Pagkakatugma",
    "guess": "Hulaan / Ano ito?",
    "recommendation": "Rekomendasyon",
    "decision": "Opinyon at desisyon",
    "guided": "May gabay",
    "score": "Tamang sagot / Iskor",
    "spectrum": "Gaano ka ka-X?",
    "archetype": "Aling X ka?",
    "emptyTitle": "Wala pang karanasan",
    "emptyHint": "Makikita rito ang una mong inilathalang karanasan.",
    "newExperience": "Bagong karanasan",
    "view": "Tingnan ↗",
    "edit": "I-edit ang nilalaman",
    "opening": "Binubuksan ang nilalaman…",
    "updating": "Ina-update…",
    "pause": "Ihinto",
    "republish": "Ilathala muli",
    "closeShare": "Isara ang pagbabahagi",
    "share": "Ibahagi",
    "copyLink": "Kopyahin ang link",
    "copied": "Nakopya ✓",
    "shareOnX": "Ibahagi sa X",
    "participants": "Mga kalahok",
    "loadingParticipants": "Naglo-load ng mga kalahok…",
    "noParticipants": "Wala pang nakakumpleto.",
    "anonymous": "Hindi nagpapakilala",
    "result": "Resulta",
    "completed": "Nakumpleto",
    "correct": "Tama",
    "answers": "Mga ibinigay na sagot",
    "question": "Tanong",
    "option": "Opsyon",
    "participantAnswer": "Sagot ng kalahok",
    "shareHeading": "Ibahagi ang iyong karanasan.",
    "shareHint": "Kopyahin ang link o ibahagi sa social media.",
    "qrCode": "QR code",
    "qrAlt": "QR code ng karanasan",
    "qrHint": "Gamitin sa pisikal na lugar o sa ibang larawan.",
    "openQr": "Buksan ang QR ↗",
    "participantsHint": "Unang ipinapakita ang pinakabagong pagkumpleto.",
    "storyNoData": "Hindi nangongolekta ng datos ng tanong at sagot ang karanasang ito.",
    "guessNoData": "Nakumpleto ang paghula. Hindi naka-save dito ang malayang tekstong sagot.",
    "completionNoData": "Walang detalye ng sagot para sa pagkumpletong ito.",
    "moderationLock": "Naka-lock ng moderasyon",
    "moderationPaused": "Inihinto ng moderasyon ng AQRYO ang karanasang ito.",
    "cannotRepublish": "Hindi ito mailalathala muli ng creator.",
    "reason": "Dahilan"
  }
} as const;

export function getCreatorExperienceCopy(locale: AqryoLocale) { return copy[locale] ?? copy.en; }
