import type { AqryoLocale } from "./i18n";

const FLOW_COPY = {
  "tr": {
    "name": "Akış",
    "headline": "Metnin hazırsa, akışın da hazır.",
    "paste": "Metnini buraya yapıştır",
    "placeholder": "Metninin tamamını tek seferde yapıştır.",
    "title": "Akış başlığı",
    "images": "Akış görsellerini seç",
    "uploading": "Görseller akışına ekleniyor. Yükleme bitince yayınlayabilirsin.",
    "position": "Akıştaki yeri",
    "look": "Akışın dokusunu seç",
    "share": "Akışın, kapak görseliyle birlikte bağlantı olarak paylaşılır.",
    "cover": "Akış kapağı",
    "empty": "Metnini yapıştırdığında akışın burada görünür.",
    "version": "Yayındaki akışın korunur. Düzenleme yeni sürüm olarak yayınlanır.",
    "open": "Akışı aç",
    "newFlow": "Yeni akış",
    "create": "Akış oluştur",
    "ending": "Akışın sonu",
    "review": "Akışı baştan sona okuyarak kontrol et.",
    "description": "Metin ve görsellerle kaydırarak okunan bir akış oluştur."
  },
  "en": {
    "name": "Flow",
    "headline": "Your text is ready. So is your flow.",
    "paste": "Paste your text here",
    "placeholder": "Paste your entire text at once.",
    "title": "Flow title",
    "images": "Choose flow images",
    "uploading": "Adding images to your flow. You can publish when the upload finishes.",
    "position": "Position in flow",
    "look": "Choose your flow’s look",
    "share": "Share your flow as a link with its cover preview.",
    "cover": "Flow cover",
    "empty": "Paste your text to see your flow here.",
    "version": "Your live flow stays unchanged. Edits publish as a new version.",
    "open": "Open the flow",
    "newFlow": "New flow",
    "create": "Create a flow",
    "ending": "Flow ending",
    "review": "Read your flow from start to finish before publishing.",
    "description": "Create a swipeable flow with text and images."
  },
  "es": {
    "name": "Flujo",
    "headline": "Tu texto está listo. Tu flujo también.",
    "paste": "Pega tu texto aquí",
    "placeholder": "Pega todo tu texto de una vez.",
    "title": "Título del flujo",
    "images": "Elige imágenes para el flujo",
    "uploading": "Añadiendo imágenes al flujo. Podrás publicar cuando termine la carga.",
    "position": "Posición en el flujo",
    "look": "Elige el estilo de tu flujo",
    "share": "Comparte tu flujo mediante un enlace con vista previa de portada.",
    "cover": "Portada del flujo",
    "empty": "Pega tu texto para ver tu flujo aquí.",
    "version": "Tu flujo publicado se conserva. Los cambios se publican como una nueva versión.",
    "open": "Abrir el flujo",
    "newFlow": "Nuevo flujo",
    "create": "Crear un flujo",
    "ending": "Final del flujo",
    "review": "Lee tu flujo de principio a fin antes de publicar.",
    "description": "Crea un flujo de texto e imágenes que se lee deslizando."
  },
  "pt": {
    "name": "Fluxo",
    "headline": "Seu texto está pronto. Seu fluxo também.",
    "paste": "Cole seu texto aqui",
    "placeholder": "Cole todo o texto de uma vez.",
    "title": "Título do fluxo",
    "images": "Escolha imagens para o fluxo",
    "uploading": "Adicionando imagens ao fluxo. Você poderá publicar quando o envio terminar.",
    "position": "Posição no fluxo",
    "look": "Escolha o visual do fluxo",
    "share": "Compartilhe seu fluxo por um link com prévia da capa.",
    "cover": "Capa do fluxo",
    "empty": "Cole seu texto para ver seu fluxo aqui.",
    "version": "Seu fluxo publicado é preservado. As alterações geram uma nova versão.",
    "open": "Abrir o fluxo",
    "newFlow": "Novo fluxo",
    "create": "Criar um fluxo",
    "ending": "Final do fluxo",
    "review": "Leia seu fluxo do início ao fim antes de publicar.",
    "description": "Crie um fluxo de texto e imagens para ler deslizando."
  },
  "fr": {
    "name": "Flux",
    "headline": "Votre texte est prêt. Votre flux aussi.",
    "paste": "Collez votre texte ici",
    "placeholder": "Collez tout votre texte en une seule fois.",
    "title": "Titre du flux",
    "images": "Choisissez les images du flux",
    "uploading": "Ajout des images au flux. Vous pourrez publier une fois le chargement terminé.",
    "position": "Position dans le flux",
    "look": "Choisissez le style du flux",
    "share": "Partagez votre flux par un lien avec un aperçu de sa couverture.",
    "cover": "Couverture du flux",
    "empty": "Collez votre texte pour voir votre flux ici.",
    "version": "Votre flux publié est conservé. Les modifications créent une nouvelle version.",
    "open": "Ouvrir le flux",
    "newFlow": "Nouveau flux",
    "create": "Créer un flux",
    "ending": "Fin du flux",
    "review": "Lisez votre flux du début à la fin avant de publier.",
    "description": "Créez un flux de textes et d’images à parcourir en faisant défiler les pages."
  },
  "de": {
    "name": "Fluss",
    "headline": "Dein Text ist bereit. Dein Fluss auch.",
    "paste": "Füge deinen Text hier ein",
    "placeholder": "Füge deinen gesamten Text auf einmal ein.",
    "title": "Titel des Flusses",
    "images": "Bilder für den Fluss auswählen",
    "uploading": "Bilder werden zum Fluss hinzugefügt. Nach dem Upload kannst du veröffentlichen.",
    "position": "Position im Fluss",
    "look": "Wähle das Design deines Flusses",
    "share": "Teile deinen Fluss als Link mit Cover-Vorschau.",
    "cover": "Cover des Flusses",
    "empty": "Füge deinen Text ein, um deinen Fluss hier zu sehen.",
    "version": "Dein veröffentlichter Fluss bleibt erhalten. Änderungen werden als neue Version veröffentlicht.",
    "open": "Fluss öffnen",
    "newFlow": "Neuer Fluss",
    "create": "Fluss erstellen",
    "ending": "Ende des Flusses",
    "review": "Lies deinen Fluss vor der Veröffentlichung von Anfang bis Ende.",
    "description": "Erstelle einen Fluss aus Text und Bildern zum Durchblättern."
  },
  "it": {
    "name": "Flusso",
    "headline": "Il testo è pronto. Anche il tuo flusso.",
    "paste": "Incolla qui il tuo testo",
    "placeholder": "Incolla tutto il testo in una volta.",
    "title": "Titolo del flusso",
    "images": "Scegli le immagini del flusso",
    "uploading": "Aggiunta delle immagini al flusso. Potrai pubblicare al termine del caricamento.",
    "position": "Posizione nel flusso",
    "look": "Scegli lo stile del flusso",
    "share": "Condividi il flusso tramite un link con anteprima della copertina.",
    "cover": "Copertina del flusso",
    "empty": "Incolla il testo per vedere qui il tuo flusso.",
    "version": "Il flusso pubblicato viene conservato. Le modifiche creano una nuova versione.",
    "open": "Apri il flusso",
    "newFlow": "Nuovo flusso",
    "create": "Crea un flusso",
    "ending": "Fine del flusso",
    "review": "Leggi il flusso dall’inizio alla fine prima di pubblicarlo.",
    "description": "Crea un flusso di testi e immagini da sfogliare."
  },
  "ar": {
    "name": "تدفق",
    "headline": "نصك جاهز، وكذلك تدفقك.",
    "paste": "الصق نصك هنا",
    "placeholder": "الصق النص كاملًا دفعة واحدة.",
    "title": "عنوان التدفق",
    "images": "اختر صور التدفق",
    "uploading": "تُضاف الصور إلى التدفق. يمكنك النشر بعد اكتمال الرفع.",
    "position": "الموضع في التدفق",
    "look": "اختر تصميم التدفق",
    "share": "شارك تدفقك برابط يتضمن معاينة الغلاف.",
    "cover": "غلاف التدفق",
    "empty": "الصق نصك لعرض التدفق هنا.",
    "version": "يبقى تدفقك المنشور كما هو. تُنشر التعديلات كنسخة جديدة.",
    "open": "افتح التدفق",
    "newFlow": "تدفق جديد",
    "create": "أنشئ تدفقًا",
    "ending": "نهاية التدفق",
    "review": "اقرأ التدفق من البداية إلى النهاية قبل النشر.",
    "description": "أنشئ تدفقًا من النصوص والصور يُقرأ بالتمرير."
  },
  "hi": {
    "name": "प्रवाह",
    "headline": "आपका टेक्स्ट तैयार है। आपका प्रवाह भी।",
    "paste": "अपना टेक्स्ट यहाँ पेस्ट करें",
    "placeholder": "पूरा टेक्स्ट एक बार में पेस्ट करें।",
    "title": "प्रवाह का शीर्षक",
    "images": "प्रवाह की तस्वीरें चुनें",
    "uploading": "प्रवाह में तस्वीरें जुड़ रही हैं। अपलोड पूरा होने पर प्रकाशित कर सकते हैं।",
    "position": "प्रवाह में स्थान",
    "look": "प्रवाह का रूप चुनें",
    "share": "कवर पूर्वावलोकन वाले लिंक से अपना प्रवाह साझा करें।",
    "cover": "प्रवाह का कवर",
    "empty": "अपना प्रवाह यहाँ देखने के लिए टेक्स्ट पेस्ट करें।",
    "version": "आपका प्रकाशित प्रवाह सुरक्षित रहता है। बदलाव नए संस्करण के रूप में प्रकाशित होते हैं।",
    "open": "प्रवाह खोलें",
    "newFlow": "नया प्रवाह",
    "create": "प्रवाह बनाएँ",
    "ending": "प्रवाह का अंत",
    "review": "प्रकाशित करने से पहले प्रवाह शुरू से अंत तक पढ़ें।",
    "description": "टेक्स्ट और तस्वीरों का स्वाइप करके पढ़ने योग्य प्रवाह बनाएँ।"
  },
  "id": {
    "name": "Alur",
    "headline": "Teksmu siap. Alurmu juga.",
    "paste": "Tempel teksmu di sini",
    "placeholder": "Tempel seluruh teks sekaligus.",
    "title": "Judul alur",
    "images": "Pilih gambar alur",
    "uploading": "Menambahkan gambar ke alur. Kamu bisa menerbitkan setelah unggahan selesai.",
    "position": "Posisi dalam alur",
    "look": "Pilih tampilan alur",
    "share": "Bagikan alur melalui tautan dengan pratinjau sampul.",
    "cover": "Sampul alur",
    "empty": "Tempel teks untuk melihat alurmu di sini.",
    "version": "Alur yang sudah terbit tetap tersimpan. Perubahan diterbitkan sebagai versi baru.",
    "open": "Buka alur",
    "newFlow": "Alur baru",
    "create": "Buat alur",
    "ending": "Akhir alur",
    "review": "Baca alur dari awal hingga akhir sebelum menerbitkan.",
    "description": "Buat alur teks dan gambar yang dibaca dengan menggeser."
  },
  "ru": {
    "name": "Поток",
    "headline": "Текст готов. Ваш поток тоже.",
    "paste": "Вставьте текст сюда",
    "placeholder": "Вставьте весь текст за один раз.",
    "title": "Название потока",
    "images": "Выберите изображения для потока",
    "uploading": "Добавляем изображения в поток. Публикация будет доступна после загрузки.",
    "position": "Место в потоке",
    "look": "Выберите оформление потока",
    "share": "Поделитесь потоком по ссылке с предпросмотром обложки.",
    "cover": "Обложка потока",
    "empty": "Вставьте текст, чтобы увидеть поток здесь.",
    "version": "Опубликованный поток сохранится. Изменения публикуются как новая версия.",
    "open": "Открыть поток",
    "newFlow": "Новый поток",
    "create": "Создать поток",
    "ending": "Конец потока",
    "review": "Прочитайте поток от начала до конца перед публикацией.",
    "description": "Создайте поток из текста и изображений для чтения с пролистыванием."
  },
  "bn": {
    "name": "প্রবাহ",
    "headline": "আপনার লেখা প্রস্তুত। আপনার প্রবাহও।",
    "paste": "আপনার লেখা এখানে পেস্ট করুন",
    "placeholder": "সম্পূর্ণ লেখা একবারে পেস্ট করুন।",
    "title": "প্রবাহের শিরোনাম",
    "images": "প্রবাহের ছবি বেছে নিন",
    "uploading": "প্রবাহে ছবি যোগ হচ্ছে। আপলোড শেষ হলে প্রকাশ করতে পারবেন।",
    "position": "প্রবাহে অবস্থান",
    "look": "প্রবাহের নকশা বেছে নিন",
    "share": "কভারের প্রিভিউসহ লিঙ্ক দিয়ে প্রবাহ শেয়ার করুন।",
    "cover": "প্রবাহের কভার",
    "empty": "প্রবাহ দেখতে এখানে লেখা পেস্ট করুন।",
    "version": "প্রকাশিত প্রবাহ অপরিবর্তিত থাকবে। পরিবর্তন নতুন সংস্করণ হিসেবে প্রকাশিত হবে।",
    "open": "প্রবাহ খুলুন",
    "newFlow": "নতুন প্রবাহ",
    "create": "প্রবাহ তৈরি করুন",
    "ending": "প্রবাহের শেষ",
    "review": "প্রকাশের আগে প্রবাহ শুরু থেকে শেষ পর্যন্ত পড়ুন।",
    "description": "সোয়াইপ করে পড়ার জন্য লেখা ও ছবির প্রবাহ তৈরি করুন।"
  },
  "ur": {
    "name": "بہاؤ",
    "headline": "آپ کا متن تیار ہے۔ آپ کا بہاؤ بھی۔",
    "paste": "اپنا متن یہاں پیسٹ کریں",
    "placeholder": "پورا متن ایک ساتھ پیسٹ کریں۔",
    "title": "بہاؤ کا عنوان",
    "images": "بہاؤ کی تصاویر منتخب کریں",
    "uploading": "بہاؤ میں تصاویر شامل ہو رہی ہیں۔ اپ لوڈ مکمل ہونے پر شائع کر سکتے ہیں۔",
    "position": "بہاؤ میں جگہ",
    "look": "بہاؤ کا انداز منتخب کریں",
    "share": "سرورق کے پیش منظر والے لنک سے بہاؤ شیئر کریں۔",
    "cover": "بہاؤ کا سرورق",
    "empty": "بہاؤ دیکھنے کے لیے اپنا متن یہاں پیسٹ کریں۔",
    "version": "شائع شدہ بہاؤ محفوظ رہتا ہے۔ تبدیلیاں نئے نسخے کے طور پر شائع ہوتی ہیں۔",
    "open": "بہاؤ کھولیں",
    "newFlow": "نیا بہاؤ",
    "create": "بہاؤ بنائیں",
    "ending": "بہاؤ کا اختتام",
    "review": "شائع کرنے سے پہلے بہاؤ شروع سے آخر تک پڑھیں۔",
    "description": "متن اور تصاویر کا سوائپ کر کے پڑھنے والا بہاؤ بنائیں۔"
  },
  "vi": {
    "name": "Luồng",
    "headline": "Văn bản đã sẵn sàng. Luồng của bạn cũng vậy.",
    "paste": "Dán văn bản vào đây",
    "placeholder": "Dán toàn bộ văn bản cùng lúc.",
    "title": "Tiêu đề luồng",
    "images": "Chọn hình ảnh cho luồng",
    "uploading": "Đang thêm ảnh vào luồng. Bạn có thể đăng sau khi tải lên xong.",
    "position": "Vị trí trong luồng",
    "look": "Chọn giao diện cho luồng",
    "share": "Chia sẻ luồng bằng liên kết có ảnh xem trước bìa.",
    "cover": "Ảnh bìa luồng",
    "empty": "Dán văn bản để xem luồng tại đây.",
    "version": "Luồng đã đăng được giữ nguyên. Chỉnh sửa được đăng thành phiên bản mới.",
    "open": "Mở luồng",
    "newFlow": "Luồng mới",
    "create": "Tạo luồng",
    "ending": "Kết thúc luồng",
    "review": "Đọc luồng từ đầu đến cuối trước khi đăng.",
    "description": "Tạo luồng văn bản và hình ảnh để đọc bằng cách vuốt."
  },
  "fil": {
    "name": "Daloy",
    "headline": "Handa na ang teksto mo. Pati ang daloy mo.",
    "paste": "I-paste ang teksto mo rito",
    "placeholder": "I-paste ang buong teksto nang sabay-sabay.",
    "title": "Pamagat ng daloy",
    "images": "Pumili ng mga larawan para sa daloy",
    "uploading": "Nagdaragdag ng mga larawan sa daloy. Maaari kang mag-publish pagkatapos ma-upload.",
    "position": "Posisyon sa daloy",
    "look": "Piliin ang disenyo ng daloy",
    "share": "I-share ang daloy bilang link na may preview ng cover.",
    "cover": "Cover ng daloy",
    "empty": "I-paste ang teksto para makita ang daloy rito.",
    "version": "Mananatili ang nai-publish na daloy. Ang mga pagbabago ay bagong bersyon.",
    "open": "Buksan ang daloy",
    "newFlow": "Bagong daloy",
    "create": "Gumawa ng daloy",
    "ending": "Dulo ng daloy",
    "review": "Basahin ang daloy mula simula hanggang dulo bago i-publish.",
    "description": "Gumawa ng daloy ng teksto at larawan na binabasa sa pag-swipe."
  }
} satisfies Record<AqryoLocale, Record<string, string>>;

export function getFlowCopy(locale: string = "en") {
  return FLOW_COPY[locale as AqryoLocale] ?? FLOW_COPY.en;
}
