import type { AqryoLocale } from "./i18n";
import type { PaidVisualPack } from "@/services/visual-packs";

type PackCopy = { buy: string; permanent: string; contents: string; owned: string; preview: string; loading: string; pending: string; error: string; refresh: string; unavailable: string; classic: string; magic: string; arena: string };
const copies: Record<AqryoLocale, PackCopy> = {
  tr: { buy: "Satın al", permanent: "Tek seferlik ödeme · Kalıcı erişim", contents: "30 görsel: 10 Single + 10 Couple + 10 Scene", owned: "Satın alındı", preview: "Ön izle", loading: "Yükleniyor…", pending: "Ödemen doğrulanıyor. Paket hesabına otomatik açılacak.", error: "İşlem tamamlanamadı. Tekrar deneyebilirsin.", refresh: "Tekrar kontrol et", unavailable: "Şu an satın alma açılamıyor. Biraz sonra tekrar dene.", classic: "Klasik", magic: "Büyü Akademisi", arena: "Dövüş Arenası" },
  en: { buy: "Buy", permanent: "One-time payment · Permanent access", contents: "30 visuals: 10 Single + 10 Couple + 10 Scene", owned: "Purchased", preview: "Preview", loading: "Loading…", pending: "Your payment is being verified. The pack will unlock automatically.", error: "Unable to complete this action. Please try again.", refresh: "Check again", unavailable: "Checkout is unavailable right now. Please try again later.", classic: "Classic", magic: "Magic Academy", arena: "Fighting Arena" },
  es: { buy: "Comprar", permanent: "Pago único · Acceso permanente", contents: "30 imágenes: 10 Single + 10 Couple + 10 Scene", owned: "Comprado", preview: "Vista previa", loading: "Cargando…", pending: "Estamos verificando tu pago. El paquete se desbloqueará automáticamente.", error: "No se pudo completar la operación. Inténtalo de nuevo.", refresh: "Comprobar de nuevo", unavailable: "El pago no está disponible ahora. Inténtalo más tarde.", classic: "Clásico", magic: "Academia de Magia", arena: "Arena de Combate" },
  pt: { buy: "Comprar", permanent: "Pagamento único · Acesso permanente", contents: "30 imagens: 10 Single + 10 Couple + 10 Scene", owned: "Comprado", preview: "Prévia", loading: "Carregando…", pending: "Estamos verificando seu pagamento. O pacote será liberado automaticamente.", error: "Não foi possível concluir. Tente novamente.", refresh: "Verificar novamente", unavailable: "O pagamento está indisponível. Tente mais tarde.", classic: "Clássico", magic: "Academia de Magia", arena: "Arena de Luta" },
  fr: { buy: "Acheter", permanent: "Paiement unique · Accès permanent", contents: "30 visuels : 10 Single + 10 Couple + 10 Scene", owned: "Acheté", preview: "Aperçu", loading: "Chargement…", pending: "Votre paiement est en cours de vérification. Le pack sera débloqué automatiquement.", error: "Impossible de terminer. Veuillez réessayer.", refresh: "Vérifier à nouveau", unavailable: "Le paiement est indisponible. Réessayez plus tard.", classic: "Classique", magic: "Académie de Magie", arena: "Arène de Combat" },
  de: { buy: "Kaufen", permanent: "Einmalige Zahlung · Dauerhafter Zugriff", contents: "30 Bilder: 10 Single + 10 Couple + 10 Scene", owned: "Gekauft", preview: "Vorschau", loading: "Wird geladen…", pending: "Deine Zahlung wird geprüft. Das Paket wird automatisch freigeschaltet.", error: "Der Vorgang konnte nicht abgeschlossen werden. Bitte erneut versuchen.", refresh: "Erneut prüfen", unavailable: "Die Zahlung ist derzeit nicht verfügbar. Versuche es später erneut.", classic: "Klassisch", magic: "Magieakademie", arena: "Kampfarena" },
  it: { buy: "Acquista", permanent: "Pagamento unico · Accesso permanente", contents: "30 immagini: 10 Single + 10 Couple + 10 Scene", owned: "Acquistato", preview: "Anteprima", loading: "Caricamento…", pending: "Stiamo verificando il pagamento. Il pacchetto sarà sbloccato automaticamente.", error: "Impossibile completare. Riprova.", refresh: "Controlla di nuovo", unavailable: "Il pagamento non è disponibile. Riprova più tardi.", classic: "Classico", magic: "Accademia di Magia", arena: "Arena di Combattimento" },
  ar: { buy: "شراء", permanent: "دفعة واحدة · وصول دائم", contents: "30 صورة: 10 Single + 10 Couple + 10 Scene", owned: "تم الشراء", preview: "معاينة", loading: "جارٍ التحميل…", pending: "جارٍ التحقق من الدفع. سيتم فتح الحزمة تلقائيًا.", error: "تعذر إكمال العملية. حاول مرة أخرى.", refresh: "تحقق مجددًا", unavailable: "الدفع غير متاح الآن. حاول لاحقًا.", classic: "كلاسيكي", magic: "أكاديمية السحر", arena: "ساحة القتال" },
  hi: { buy: "खरीदें", permanent: "एक बार भुगतान · स्थायी पहुँच", contents: "30 चित्र: 10 Single + 10 Couple + 10 Scene", owned: "खरीदा गया", preview: "पूर्वावलोकन", loading: "लोड हो रहा है…", pending: "आपका भुगतान सत्यापित हो रहा है। पैक अपने आप खुल जाएगा।", error: "प्रक्रिया पूरी नहीं हुई। फिर कोशिश करें।", refresh: "फिर जाँचें", unavailable: "भुगतान अभी उपलब्ध नहीं है। बाद में कोशिश करें।", classic: "क्लासिक", magic: "जादू अकादमी", arena: "लड़ाई का अखाड़ा" },
  id: { buy: "Beli", permanent: "Sekali bayar · Akses permanen", contents: "30 gambar: 10 Single + 10 Couple + 10 Scene", owned: "Dibeli", preview: "Pratinjau", loading: "Memuat…", pending: "Pembayaran sedang diverifikasi. Paket akan terbuka otomatis.", error: "Tindakan tidak dapat diselesaikan. Coba lagi.", refresh: "Periksa lagi", unavailable: "Pembayaran belum tersedia. Coba lagi nanti.", classic: "Klasik", magic: "Akademi Sihir", arena: "Arena Pertarungan" },
  ru: { buy: "Купить", permanent: "Разовая оплата · Постоянный доступ", contents: "30 изображений: 10 Single + 10 Couple + 10 Scene", owned: "Куплено", preview: "Просмотр", loading: "Загрузка…", pending: "Платёж проверяется. Пакет откроется автоматически.", error: "Не удалось завершить действие. Попробуйте снова.", refresh: "Проверить снова", unavailable: "Оплата сейчас недоступна. Попробуйте позже.", classic: "Классика", magic: "Академия Магии", arena: "Боевая Арена" },
  bn: { buy: "কিনুন", permanent: "একবার পেমেন্ট · স্থায়ী অ্যাক্সেস", contents: "30 ছবি: 10 Single + 10 Couple + 10 Scene", owned: "কেনা হয়েছে", preview: "প্রিভিউ", loading: "লোড হচ্ছে…", pending: "পেমেন্ট যাচাই হচ্ছে। প্যাকটি স্বয়ংক্রিয়ভাবে খুলবে।", error: "কাজটি সম্পন্ন হয়নি। আবার চেষ্টা করুন।", refresh: "আবার যাচাই করুন", unavailable: "এখন পেমেন্ট করা যাচ্ছে না। পরে চেষ্টা করুন।", classic: "ক্লাসিক", magic: "ম্যাজিক একাডেমি", arena: "ফাইটিং অ্যারেনা" },
  ur: { buy: "خریدیں", permanent: "ایک بار ادائیگی · مستقل رسائی", contents: "30 تصاویر: 10 Single + 10 Couple + 10 Scene", owned: "خرید لیا", preview: "پیش منظر", loading: "لوڈ ہو رہا ہے…", pending: "ادائیگی کی تصدیق ہو رہی ہے۔ پیک خود بخود کھل جائے گا۔", error: "عمل مکمل نہیں ہوا۔ دوبارہ کوشش کریں۔", refresh: "دوبارہ چیک کریں", unavailable: "ادائیگی ابھی دستیاب نہیں۔ بعد میں کوشش کریں۔", classic: "کلاسک", magic: "جادو اکیڈمی", arena: "فائٹنگ ایرینا" },
  vi: { buy: "Mua", permanent: "Thanh toán một lần · Truy cập vĩnh viễn", contents: "30 hình: 10 Single + 10 Couple + 10 Scene", owned: "Đã mua", preview: "Xem trước", loading: "Đang tải…", pending: "Đang xác minh thanh toán. Gói sẽ tự động mở khóa.", error: "Không thể hoàn tất. Vui lòng thử lại.", refresh: "Kiểm tra lại", unavailable: "Hiện không thể thanh toán. Hãy thử lại sau.", classic: "Cổ điển", magic: "Học viện Phép thuật", arena: "Đấu trường" },
  fil: { buy: "Bilhin", permanent: "Isang bayad · Permanenteng access", contents: "30 larawan: 10 Single + 10 Couple + 10 Scene", owned: "Nabili", preview: "Preview", loading: "Naglo-load…", pending: "Bineberipika ang bayad. Awtomatikong bubuksan ang pack.", error: "Hindi makumpleto. Subukan muli.", refresh: "Tingnan muli", unavailable: "Hindi pa available ang pagbabayad. Subukan mamaya.", classic: "Classic", magic: "Akademya ng Mahika", arena: "Fighting Arena" },
};

export function visualPackCopy(locale: AqryoLocale) { return copies[locale]; }
export function visualPackName(pack: PaidVisualPack | "classic", locale: AqryoLocale) {
  const copy = copies[locale];
  return pack === "anime" ? "Anime" : pack === "magic" ? copy.magic : pack === "arena" ? copy.arena : copy.classic;
}
